### ISSUE TITLE
[BUG] doctest error in sktime.forecasting.model_selection._tune.ForecastingGridSearchCV

### ISSUE THREAD

**Issue by hmtbgc** [sktime/sktime#2185]
**Describe the bug**

There is a ValueError in doctest for sktime.forecasting.model_selection._tune.ForecastingGridSearchCV

**To Reproduce**

```python
cd sktime/sktime/forecasting/model_selection
pytest _tune.py
```
Output:
```
platform linux -- Python 3.8.12, pytest-7.0.1, pluggy-1.0.0
rootdir: /root/sktime_dev/sktime, configfile: setup.cfg
plugins: cov-3.0.0, xdist-2.5.0, forked-1.4.0
collected 1 item                                                                                                    

_tune.py F                                                                                                    [100%]

===================================================== FAILURES ======================================================
____________________ [doctest] sktime.forecasting.model_selection._tune.ForecastingGridSearchCV _____________________
421     ...     },
422     ...     {
423     ...         "imputer__method": ["mean", "last"],
424     ...         "forecaster": [ExponentialSmoothing(sp=12)],
425     ...         "forecaster__trend": ["add", "mul"],
426     ...     },
427     ...     ],
428     ...     cv=cv,
429     ...     n_jobs=-1)
430     >>> gscv.fit(y)
UNEXPECTED EXCEPTION: ValueError("Input contains NaN, infinity or a value too large for dtype('float64').")
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/root/sktime_dev/sktime/sktime/forecasting/model_selection/_tune.py", line 211, in _fit_and_score
    out = evaluate(
  File "/root/sktime_dev/sktime/sktime/forecasting/model_evaluation/_functions.py", line 122, in evaluate
    score = scoring(y_test, y_pred, y_train=y_train)
  File "/root/sktime_dev/sktime/sktime/performance_metrics/forecasting/_classes.py", line 154, in __call__
    return self.func(
  File "/root/sktime_dev/sktime/sktime/performance_metrics/forecasting/_functions.py", line 1548, in mean_absolute_percentage_error
    _, y_true, y_pred, multioutput = _check_reg_targets(y_true, y_pred, multioutput)
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/site-packages/sklearn/metrics/_regression.py", line 96, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/site-packages/sklearn/utils/validation.py", line 801, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/site-packages/sklearn/utils/validation.py", line 115, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest sktime.forecasting.model_selection._tune.ForecastingGridSearchCV[23]>", line 1, in <module>
  File "/root/sktime_dev/sktime/sktime/forecasting/base/_base.py", line 160, in fit
    self._fit(y=y_inner, X=X_inner, fh=fh)
  File "/root/sktime_dev/sktime/sktime/forecasting/model_selection/_tune.py", line 260, in _fit
    results = self._run_search(evaluate_candidates)
  File "/root/sktime_dev/sktime/sktime/forecasting/model_selection/_tune.py", line 468, in _run_search
    return evaluate_candidates(ParameterGrid(self.param_grid))
  File "/root/sktime_dev/sktime/sktime/forecasting/model_selection/_tune.py", line 246, in evaluate_candidates
    out = parallel(
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/root/miniconda/envs/sktime-dev/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```
**Expected behavior**

PASSED

**Additional context**

**Versions**
0.10.1

</details>

**Comment by fkiraly** [comment]
I have python 3.8.12 too, testing on windows and with sktime 0.10.1 - the example runs without problems, cannot reproduce the bug.

Which operating system are you using, @hmtbgc?

**Comment by hmtbgc** [comment]
My operating system is Ubuntu 18.04 and I have test the newest version of sktime and it still has the same error.

**Comment by k1m190r** [comment]
Reproducing under linux, I'll take a look a this one.

**Comment by k1m190r** [comment]
OK this is really weird, the root cause is somewhere outside of sktime in `statsmodels`.
The test that is failing, is failing with specific forecaster `ExponentialSmoothing` if `trend="mul"`.

this line does not converge sometimes... a little more below...
[`forecaster.fit(y_train, X_train, fh=fh, **fit_params)`](https://github.com/alan-turing-institute/sktime/blob/b36eeca85a9735a4b899e41437c72991a9f396c7/sktime/forecasting/model_evaluation/_functions.py#L110)

with this warning, which is not visible since failure happens in the child process:
```
/home/biosckon/miniconda3/envs/sk10_py37/lib/python3.7/site-packages/statsmodels/tsa/holtwinters/model.py:917: ConvergenceWarning: Optimization failed to converge. Check mle_retvals.
```

which causes this line:
[`y_pred = forecaster.predict(fh, X=X_test)`](https://github.com/alan-turing-institute/sktime/blob/b36eeca85a9735a4b899e41437c72991a9f396c7/sktime/forecasting/model_evaluation/_functions.py#L118)
to produce:
```
1993-01   NaN
1993-02   NaN
1993-03   NaN
Freq: M, dtype: float64
```

and finally `ValueError` as in the original report at this line:
[`score = scoring(y_test, y_pred, y_train=y_train)`](https://github.com/alan-turing-institute/sktime/blob/b36eeca85a9735a4b899e41437c72991a9f396c7/sktime/forecasting/model_evaluation/_functions.py#L122)

In my setup it fails only under Ubuntu 20 with Python 3.7.
It does **not** fail under 3.8 or 3.9, and not under Windows.

Can be replicated with this... sometimes.

```python
import numpy as np
from sktime.datasets import load_shampoo_sales
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
from sktime.forecasting.model_evaluation._functions import _split

y = load_shampoo_sales()
X = None
train = np.arange(24)
test = np.array([24, 25, 26])
fh = [1, 2, 3]
fit_params = {}

forecaster = ExponentialSmoothing(trend="mul", sp=12)
y_train, y_test, X_train, X_test = _split(y, X, train, test, fh)
fh = ForecastingHorizon(y_test.index, is_relative=False)
forecaster.fit(y_train, X_train, fh=fh, **fit_params)
y_pred = forecaster.predict(fh, X=X_test)
y_pred
```

**Comment by fkiraly** [comment]
the bug is no longer present on newest `sktime`/`statsmodels` version
