### ISSUE TITLE
[BUG] AutoETS fails on pandas input with int dtype

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2323]
**Describe the bug**

`AutoETS` breaks if fitted on a `pandas` container with `int` dtype.

**To Reproduce**

```python
import pandas as pd
from sktime.forecasting.ets import AutoETS
y = pd.DataFrame({"a": range(20)})
AutoETS().fit(y)
```

**Expected behavior**

It should not break. This can probably be fixed by casting to float internally, by `y = y.astype(float)`. Needs checking

**Additional context**

We probably also should add test that passes examples with int data.
This should be added to `scenarios_forecasting`.

**Comment by fkiraly** [comment]
good first issue, fix or adding scenario should be simple

**Comment by kearkyle** [comment]
Hi @fkiraly, I did `y=y.astype(float)` under _fit function in ets.py but it seems that it doesn't change type from int to float internally when I call `print(y.dtypes)`. It seems to throw an error from within  _statsmodels.py when calling `if isinstance(y, pd.Series) and type(y.index) == pd.Int64Index`.
![image](https://user-images.githubusercontent.com/43527143/160496077-b89c6209-7bfd-4f47-b15b-81e7c2141c35.png)

Even by changing y to float externally from when reproducing, it would still throw that same error.
![image](https://user-images.githubusercontent.com/43527143/160496746-8bd92af6-bdda-42e4-85f2-ab268aa8f3bb.png)

**Comment by fkiraly** [comment]
I think you need to change the dtype of the *data* without changing the dtype of the *index*. If you change the index, too, it is no longer following the sktime format specification.

**Comment by kearkyle** [comment]
Seems like changing `y=y.astype(float)` , I'm looking at the adding scenario case, could you explain how we can approach this?

**Comment by fkiraly** [comment]
Perhaps, first of all, @kearkyle:
* can you reproduce the bug?
* it looks like you do not have a full developer setup which would allow you to run a debugger. I advise to start getting that set up

**Comment by kearkyle** [comment]
I have been looking around, so this is what I got from anaconda console:
(base) E:\github\sktime>python test.py
     a
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11
12  12
13  13
14  14
15  15
16  16
17  17
18  18
19  19
a    int64
dtype: object
Traceback (most recent call last):
  File "E:\github\sktime\test.py", line 7, in <module>
    AutoETS().fit(y)
  File "E:\github\sktime\sktime\forecasting\base\_base.py", line 163, in fit
    self._fit(y=y_inner, X=X_inner, fh=fh)
  File "E:\github\sktime\sktime\forecasting\base\adapters\_statsmodels.py", line 52, in _fit
    self._fit_forecaster(y, X)
  File "E:\github\sktime\sktime\forecasting\ets.py", line 374, in _fit_forecaster
    self._fitted_forecaster = self._forecaster.fit(
  File "C:\Users\keark\anaconda3\lib\site-packages\statsmodels\tsa\exponential_smoothing\ets.py", line 1030, in fit
    mlefit = super().fit(
  File "C:\Users\keark\anaconda3\lib\site-packages\statsmodels\base\model.py", line 519, in fit
    xopt, retvals, optim_settings = optimizer._fit(f, score, start_params,
  File "C:\Users\keark\anaconda3\lib\site-packages\statsmodels\base\optimizer.py", line 224, in _fit
    xopt, retvals = func(objective, gradient, start_params, fargs, kwargs,
  File "C:\Users\keark\anaconda3\lib\site-packages\statsmodels\base\optimizer.py", line 629, in _fit_lbfgs
    retvals = optimize.fmin_l_bfgs_b(func, start_params, maxiter=maxiter,
  File "C:\Users\keark\anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py", line 197, in fmin_l_bfgs_b
    res = _minimize_lbfgsb(fun, x0, args=args, jac=jac, bounds=bounds,
  File "C:\Users\keark\anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "C:\Users\keark\anaconda3\lib\site-packages\scipy\optimize\optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "C:\Users\keark\anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 140, in __init__
    self._update_fun()
  File "C:\Users\keark\anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 233, in _update_fun
    self._update_fun_impl()
  File "C:\Users\keark\anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 137, in update_fun
    self.f = fun_wrapped(self.x)
  File "C:\Users\keark\anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 134, in fun_wrapped
    return fun(np.copy(x), *args)
  File "C:\Users\keark\anaconda3\lib\site-packages\statsmodels\base\model.py", line 501, in f
    return -self.loglike(params, *args) / nobs
  File "C:\Users\keark\anaconda3\lib\site-packages\statsmodels\tsa\exponential_smoothing\ets.py", line 1122, in _loglike_internal
    self._smoothing_func(
  File "statsmodels\tsa\exponential_smoothing\_ets_smooth.pyx", line 65, in statsmodels.tsa.exponential_smoothing._ets_smooth._ets_smooth_add_add
ValueError: Buffer dtype mismatch, expected 'float64_t' but got 'long long'

and my reproduce file has this:
```
import pandas as pd
from sktime.forecasting.ets import AutoETS
y = pd.DataFrame({"a": range(20)})
# y = y.astype(float)
print(y)
print(y.dtypes)
AutoETS().fit(y)
```

**Comment by eenticott-shell** [comment]
As of 0.11.2 this example no longer seems to produce an error.

**Comment by fkiraly** [comment]
For me, it fails on sktime dev version (latest main), python 3.8, windows.

**Comment by fkiraly** [comment]
also doesn't produce an error for me anymore. Seems to have been indirectly fixed by one of the many index related bugfixes probably.
