### ISSUE TITLE
[BUG] Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`

### ISSUE THREAD

**Issue by AurumnPegasus** [sktime/sktime#2785]
**Describe the bug**

On following instructions for installation of [development version](https://www.sktime.org/en/stable/installation.html) I get the following error:
![img](https://i.imgur.com/QMY1m4o.png[/img)

**To Reproduce**

System Information:
```bash
Distributor ID:	Pop
Description:	Pop!_OS 21.10
Release:	21.10
Codename:	impish
```
Details about conda environmnet:
<details>

```bash
# packages in environment at /home/shivansh/anaconda3/envs/sktime-dev:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.1.0                    pypi_0    pypi
anyio                     3.6.1                    pypi_0    pypi
arviz                     0.12.1             pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                hf3e587d_33    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.5.18.1          ha878542_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.5.18.1      py38h578d9bd_0    conda-forge
cfgv                      3.3.1                    pypi_0    pypi
cftime                    1.6.0            py38h71d37f0_1    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.1.0                    pypi_0    pypi
cmdstanpy                 0.9.68                   pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
convertdate               2.4.0              pyhd8ed1ab_0    conda-forge
coverage                  6.4.1                    pypi_0    pypi
curl                      7.82.0               h7f8727e_0  
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.30          py38hfa26641_0    conda-forge
dask                      2022.5.2                 pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deprecated                1.2.13                   pypi_0    pypi
distlib                   0.3.4                    pypi_0    pypi
distributed               2022.5.2                 pypi_0    pypi
dm-tree                   0.1.7                    pypi_0    pypi
dtw-python                1.1.12                   pypi_0    pypi
ephem                     4.1.3            py38h0a891b7_4    conda-forge
esig                      0.9.7                    pypi_0    pypi
execnet                   1.9.0                    pypi_0    pypi
filelock                  3.7.1                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
fonttools                 4.33.3                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
fsspec                    2022.5.0                 pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
gcc_impl_linux-64         7.5.0               habd7529_20    conda-forge
gcc_linux-64              7.5.0               h47867f9_33    conda-forge
google-auth               2.7.0                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.46.3                   pypi_0    pypi
gxx_impl_linux-64         7.5.0               hd0bb8aa_20    conda-forge
gxx_linux-64              7.5.0               h555fc39_33    conda-forge
h11                       0.12.0                   pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
hcrystalball              0.1.12                   pypi_0    pypi
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h2750804_100    conda-forge
heapdict                  1.0.1                    pypi_0    pypi
hijri-converter           2.2.4              pyhd8ed1ab_0    conda-forge
holidays                  0.13               pyhd8ed1ab_0    conda-forge
httpcore                  0.15.0                   pypi_0    pypi
httpx                     0.23.0                   pypi_0    pypi
icu                       67.1                 he1b5a44_0    conda-forge
identify                  2.5.1                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.11.4           py38h578d9bd_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
iniconfig                 1.1.1                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h166bdaf_1    conda-forge
keras                     2.9.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.2            py38h43d8883_1    conda-forge
korean_lunar_calendar     0.2.1              pyh9f0ad1d_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           15_linux64_openblas    conda-forge
libcblas                  3.9.0           15_linux64_openblas    conda-forge
libclang                  14.0.1                   pypi_0    pypi
libcurl                   7.82.0               h0b77cf5_0  
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-devel_linux-64     7.5.0               hda03d7c_20    conda-forge
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libgomp                   11.2.0               h1234567_1  
liblapack                 3.9.0           15_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
libnghttp2                1.46.0               hce63b2e_0  
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-devel_linux-64  7.5.0               hb016644_20    conda-forge
libstdcxx-ng              11.2.0               h1234567_1  
libzip                    1.8.0                h4de3113_1    conda-forge
llvmlite                  0.38.1                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
lunarcalendar             0.0.9                      py_0    conda-forge
lunardate                 0.2.0                    pypi_0    pypi
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.2                    pypi_0    pypi
matrixprofile             1.1.10                   pypi_0    pypi
msgpack                   1.0.4                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
netcdf4                   1.5.8           nompi_py38h2823cc8_101    conda-forge
nodeenv                   1.6.0                    pypi_0    pypi
numba                     0.55.2                   pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
openssl                   1.1.1o               h166bdaf_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.2            py38h47df419_1    conda-forge
partd                     1.2.0                    pypi_0    pypi
patsy                     0.5.2                    pypi_0    pypi
pillow                    9.1.1                    pypi_0    pypi
pip                       21.2.4           py38h06a4308_0  
platformdirs              2.5.2                    pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
pmdarima                  1.8.5                    pypi_0    pypi
pre-commit                2.19.0                   pypi_0    pypi
prophet                   1.0.1            py38hd0cf306_3    conda-forge
protobuf                  3.11.2                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyluach                   2.0.0                    pypi_0    pypi
pymeeus                   0.5.10             pyhd8ed1ab_0    conda-forge
pyod                      1.0.1                    pypi_0    pypi
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pystan                    2.19.1.1         py38hc5bc63f_2    conda-forge
pytest                    7.1.2                    pypi_0    pypi
pytest-cov                3.0.0                    pypi_0    pypi
pytest-forked             1.4.0                    pypi_0    pypi
pytest-timeout            2.1.0                    pypi_0    pypi
pytest-xdist              2.5.0                    pypi_0    pypi
python                    3.8.13               h12debd9_0  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
requests                  2.28.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3986                   1.5.0                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scikit-learn              1.1.1                    pypi_0    pypi
scikit-posthocs           0.7.0                    pypi_0    pypi
scipy                     1.8.1            py38h1ee437e_0    conda-forge
seaborn                   0.11.2                   pypi_0    pypi
setuptools                61.2.0           py38h06a4308_0  
setuptools-git            1.2                      pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sktime                    0.11.4                    dev_0    <develop>
sniffio                   1.2.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
sqlite                    3.38.3               hc218d9a_0  
statsforecast             0.5.5                    pypi_0    pypi
statsmodels               0.13.2                   pypi_0    pypi
stumpy                    1.11.1                   pypi_0    pypi
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tbats                     1.1.0                    pypi_0    pypi
tblib                     1.7.0                    pypi_0    pypi
tensorboard               2.9.1                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.9.1                    pypi_0    pypi
tensorflow-estimator      2.9.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.26.0                   pypi_0    pypi
tensorflow-probability    0.17.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.11.2                   pypi_0    pypi
tornado                   6.1              py38h0a891b7_3    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
tsfresh                   0.19.0                   pypi_0    pypi
tslearn                   0.5.2                    pypi_0    pypi
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
ujson                     5.3.0                    pypi_0    pypi
urllib3                   1.26.9                   pypi_0    pypi
virtualenv                20.14.1                  pypi_0    pypi
werkzeug                  2.1.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
workalendar               16.3.0                   pypi_0    pypi
wrapt                     1.14.1                   pypi_0    pypi
xarray                    2022.3.0           pyhd8ed1ab_0    conda-forge
xarray-einstats           0.2.2              pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h7f8727e_1  
zict                      2.2.0                    pypi_0    pypi
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h7f8727e_2  
```

</details>

Open python on terminal and enter:

```python3
from sktime import show_versions
show_versions()
```

**Expected behavior**

Giving the version of sktime used without throwing errors.

**Additional context**

A workaround which worked for me was to follow dev instructions using Python3.9 and venv (instead of conda). Do not know why this worked and conda did not

**Versions**
<details>

```
>>> from sktime import show_versions
>>> show_versions()

System:
    python: 3.9.7 (default, Sep 10 2021, 14:59:43)  [GCC 11.2.0]
executable: /home/shivansh/Desktop/Intern/GSoC/sktime/sktime-dev/bin/python3
   machine: Linux-5.17.5-76051705-generic-x86_64-with-glibc2.34

Python dependencies:
          pip: 20.3.4
   setuptools: 44.1.1
      sklearn: 1.1.1
       sktime: 0.11.4
  statsmodels: 0.13.2
        numpy: 1.21.6
        scipy: 1.8.1
       pandas: 1.4.2
   matplotlib: 3.5.2
       joblib: 1.1.0
        numba: 0.55.2
     pmdarima: 1.8.5
      tsfresh: 0.19.0

```

</details>

**Comment by fkiraly** [comment]
I can´t reproduce this on windows, python version 3.8

**Comment by fkiraly** [comment]
so the condition for this seems unclear

**Comment by lmmentel** [comment]
I can confirm, I'm getting the same on linux with py3.9

```python
Python 3.9.9 (main, Jan  2 2022, 14:39:22) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sktime import show_versions
>>> show_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'show_version' is not defined
>>> show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lukasz/projects/sktime/sktime/utils/_maint/_show_versions.py", line 85, in show_versions
    deps_info = _get_deps_info()
  File "/home/lukasz/projects/sktime/sktime/utils/_maint/_show_versions.py", line 73, in _get_deps_info
    mod = importlib.import_module(modname)
  File "/home/lukasz/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lukasz/projects/sktime-venv/lib/python3.9/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/home/lukasz/projects/sktime-venv/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/home/lukasz/projects/sktime-venv/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 72, in do_override
    ensure_local_distutils()
  File "/home/lukasz/projects/sktime-venv/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /home/lukasz/.pyenv/versions/3.9.9/lib/python3.9/distutils/core.py
>>> 
```

**Comment by benHeid** [comment]
Seems to be fixed. At least neither I nor Claude Code can reproduce it. Furthermore Python 3.8 and 3.9 are not supported anymore or?

```python

import traceback

from sktime import show_versions

print("Calling sktime.show_versions() to check it completes without raising...")

try:
    show_versions()
    raised = None
except Exception as exc:  # noqa: BLE001 - we want to catch and report any exception here
    raised = exc
    traceback.print_exc()

assert raised is None, (
    "show_versions() raised an exception instead of printing dependency "
    f"versions cleanly: {type(raised).__name__}: {raised}"
)

print("show_versions() completed without raising an exception.")

```

Triaged with Claude Code
