### ISSUE TITLE
[BUG] Unable to use RandomShapeletTransform with classifiers in a pipeline, report "TypeError: X is not of a supported"

### ISSUE THREAD

**Issue by oda356** [sktime/sktime#4039]
**Describe the bug**
I want to train a model to classify some time series data. I think using shapelet-based time series processing is suitable for my data. So I combined ShapeletTransform with MLPClassifier to build a classify pipeline. However when I tried to fit the pipeline, it reports an error. Could you please review it and give me some suggestions?

**To Reproduce**

```python
from sktime.classification.deep_learning import MLPClassifier
from sktime.transformations.panel.shapelet_transform import RandomShapeletTransform    
from sktime.datasets import load_unit_test

X_train, y_train = load_unit_test(split="train", return_X_y=True)
estimator = MLPClassifier()
transformer = RandomShapeletTransform()
pipeline = transformer * estimator
pipeline.fit(X_train,y_train)
```
Here's the output:
```
Traceback (most recent call last):
  File "/runners/run_train.py", line 20, in <module>
    trainSettingAndRecords = test_pipeline()
  File "/train/stc_train.py", line 80, in test_pipeline
    pipeline.fit(X_train,y_train)
  File "/lib/python3.10/site-packages/sktime/classification/base.py", line 191, in fit
    self._fit(X, y)
  File "/lib/python3.10/site-packages/sktime/classification/compose/_pipeline.py", line 200, in _fit
    self.classifier_.fit(X=Xt, y=y)
  File "/lib/python3.10/site-packages/sktime/classification/base.py", line 156, in fit
    X_metadata = self._check_classifier_input(X, y)
  File "/lib/python3.10/site-packages/sktime/classification/base.py", line 698, in _check_classifier_input
    raise TypeError(
TypeError: X is not of a supported input data type.X must be in a supported mtype format for Panel, found <class 'pandas.core.frame.DataFrame'>Use datatypes.check_is_mtype to check conformance with specifications.

Process finished with exit code 1
```

**Expected behavior**
Pipeline is trained after `fit` method complete successfully. 

**Additional context**

**Versions**
<details>

Python dependencies:
          pip: 22.3.1
   setuptools: 65.5.0
      sklearn: 1.2.0
       sktime: 0.15.0
  statsmodels: 0.13.5
        numpy: 1.23.5
        scipy: 1.9.3
       pandas: 1.5.2
   matplotlib: None
       joblib: 1.2.0
        numba: 0.56.4
     pmdarima: None
      tsfresh: None
</details>

**Comment by fkiraly** [comment]
I think this is not a bug, but intended behaviour, although the error message does not tell you the problem.

The issue is that `RandomShapeletTransform` transforms time series to tabular features, and `MLPClassifier` needs time series as input.

You could pipeline the `RandomShapeletTransform` with any `sklearn` compatible classifier, for instance this should work:

```
from sklearn.ensemble import RandomForestClassifier
from sktime.transformations.panel.shapelet_transform import RandomShapeletTransform    
from sktime.datasets import load_unit_test

X_train, y_train = load_unit_test(split="train", return_X_y=True)
estimator = RandomForestClassifier()
transformer = RandomShapeletTransform()
pipeline = transformer * estimator
pipeline.fit(X_train, y_train)
```

**Comment by fkiraly** [comment]
Having said that, I see why the error message is confusing, it does not point to the reason of the issue. Perhaps `ClassifierPipeline` should raise a better error message here, this could be conditional on an estimator type check.

**Comment by oda356** [comment]
Thanks @fkiraly ! So I guess the difference is that classifiers in **sktime.classification.* ** are used to directly classify a time series? On the other hand, if I want to transform my time series to features then classifier with those features, I'd better use classifiers from **sklearn**?

**Comment by fkiraly** [comment]
> So I guess the difference is that classifiers in **sktime.classification.*** are used to directly classify a time series? 

Correct!

> On the other hand, if I want to transform my time series to features then classifier with those features, I'd better use classifiers from **sklearn**?

Precisely. You can of course use **sklearn** classifiers in a pipeline with an `sktime` transformer (as in my code snippet), but that needs to be a transformer that outputs tabular data.

**Comment by fkiraly** [comment]
(I'd leave this issue open with the aim "improve the error message")
