### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by romanlutz** [sktime/sktime#4159]
**Describe the bug**

The code posted below returns the following error message that isn't particularly useful or actionable:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\sktime\lib\site-packages\sktime\forecasting\base\_base.py", line 407, in predict
    y_pred = self._vectorize("predict", X=X_inner, fh=fh)
  File "C:\ProgramData\Anaconda3\envs\sktime\lib\site-packages\sktime\forecasting\base\_base.py", line 1770, in _vectorize
    y_preds += [method(X=Xs[i], **kwargs)]
  File "C:\ProgramData\Anaconda3\envs\sktime\lib\site-packages\sktime\forecasting\base\_base.py", line 404, in predict
    y_pred = self._predict(fh=fh, X=X_inner)
  File "C:\ProgramData\Anaconda3\envs\sktime\lib\site-packages\sktime\forecasting\base\_sktime.py", line 31, in _predict
    return self._predict_fixed_cutoff(
  File "C:\ProgramData\Anaconda3\envs\sktime\lib\site-packages\sktime\forecasting\base\_sktime.py", line 65, in _predict_fixed_cutoff
    y_pred = self._predict_last_window(
  File "C:\ProgramData\Anaconda3\envs\sktime\lib\site-packages\sktime\forecasting\compose\_reduce.py", line 869, in _predict_last_window
    y_last, X_last = self._get_last_window()
  File "C:\ProgramData\Anaconda3\envs\sktime\lib\site-packages\sktime\forecasting\base\_sktime.py", line 124, in _get_last_window
    start = _shift(cutoff, by=-self.window_length_ + 1)
  File "C:\ProgramData\Anaconda3\envs\sktime\lib\site-packages\sktime\utils\datetime.py", line 225, in _shift
    by *= idx.freq
TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'
```

I dug into this a little and found that apparently `freq` on the index is `None` here. The `freq` is very much set on the `fh` I'm passing in, though.

**To Reproduce**

```python
import json
import numpy as np
import pandas as pd
from sktime.forecasting.compose import make_reduction
from sktime.regression.distance_based import KNeighborsTimeSeriesRegressor
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.model_selection import temporal_train_test_split
time_column_name = "WeekStarting"
time_series_id_column_names = ["Store", "Brand"]
dataset_location = "https://raw.githubusercontent.com/Azure/azureml-examples/2fe81643865e1f4591e7734bd1a729093cafb826/v1/python-sdk/tutorials/automl-with-azureml/forecasting-orange-juice-sales/dominicks_OJ.csv"
data = pd.read_csv(dataset_location, parse_dates=[time_column_name])

# Drop the columns 'logQuantity' as it is a leaky feature.
data.drop("logQuantity", axis=1, inplace=True)

data.set_index(time_series_id_column_names + [time_column_name], inplace=True)
data.sort_index(inplace=True, ascending=[True, True, True])
# use subset to speed training up
use_stores = [2, 5, 8]
data_subset = data.loc[([2,5,8], slice(None), slice(None)), :]
target_column_name = "Quantity"

y = pd.DataFrame(data_subset[target_column_name])
X = data_subset.drop(columns=[target_column_name])
fh_dates = pd.DatetimeIndex(y.index.get_level_values(2).unique().sort_values().to_list()[-20:], freq='W-THU')
fh = ForecastingHorizon(fh_dates, is_relative=False)
y_train, y_test, X_train, X_test = \
    temporal_train_test_split(
        y=y,
        X=X,
        test_size=20)
forecaster = make_reduction(KNeighborsTimeSeriesRegressor())
forecaster.fit(y=y_train, X=X_train, fh=fh)
forecaster.predict(fh=fh, X=X_test)
```

**Expected behavior**

I'd expect the `predict` to succeed or at least an actionable error message.

**Additional context**

**Versions**
<details>

```
System:
    python: 3.8.16 (default, Jan 17 2023, 22:25:28) [MSC v.1916 64 bit (AMD64)]
executable: C:\ProgramData\Anaconda3\envs\sktime\python.exe
   machine: Windows-10-10.0.19044-SP0

Python dependencies:
          pip: 22.3.1
   setuptools: 65.6.3
      sklearn: 1.0.2
       sktime: 0.15.1
  statsmodels: 0.13.5
        numpy: 1.23.5
        scipy: 1.10.0
       pandas: 1.5.3
   matplotlib: None
       joblib: 1.2.0
        numba: 0.53.1
     pmdarima: 2.0.2
      tsfresh: None
```

</details>

**Comment by fkiraly** [comment]
Hm, I'm not sure what it should be - @danbartl, looks like your favourite area of the code base?

**Comment by danbartl** [comment]
hi @fkiraly @romanlutz but it seems the training data is highly irregular, and no freq can be set or inferred here. Can you check whether cou can assign freq to the training data?

**Comment by romanlutz** [comment]
You mean the way I set it on the forecast horizon constructor? Or in a different way? As far as I know the data should be weekly (as in, one day per week). It accepted W-THU without complaining.

**Comment by danbartl** [comment]
No in the training data. That seems to be irregular, for example between first and second observation was a month gap

**Comment by romanlutz** [comment]
This probably sounds naive but I'm new to forecasting. Isn't it normal that occasionally data points are missing?

Is there a set of things I can do about it? If you have a page I'm happy to read up. 

That aside, the error didn't really help in identifying the problem as a user. I wonder if this could be surfaced differently, for example with a correctness check ahead of time?

I really appreciate your responses. Seeing this level of activity certainly adds confidence that sktime is the library to use. Thanks for your patience with my questions! Perhaps eventually I can actually fix an issue I open 😄

**Comment by fkiraly** [comment]
hm, if it comes from the gap in the data:

* should there be a tag that says whether forecasters can deal with irregular data? Then, we check the data against the tag, and raise an error if not.
* Having said that, should the reducer not be able to deal with this? Theoretically at least.

**Comment by danbartl** [comment]
The issues is not the forecaster, but the reducer since the reducer creates windows using the freq argument. Whether that is useful can of course be debated, in principle you should be able to pass arguments specifiying how to compose your windows:

1. specify a certain number of observations for the window: e.g. a window length of 5 will always take 5 observations, . 
2. specify a period length of observations: e.g. a window length of 5 days will always take observations of the past 5 days, regardless of the number of observations. 

Freq really should not factor into either of those, so you are right that the current approach should be changed.

**Comment by fkiraly** [comment]
yes, error message or possibly a tag that indicates whether irregular data is allowed.
