### ISSUE TITLE
[BUG] Imputer with ForecastingGridSearchCV

### ISSUE THREAD

**Issue by Duonijo** [sktime/sktime#4174]
Hey everyone, I found your library last week and I am playing around with it because it serves some purpose that I need for my work.
In my case I want to use **ForecastingGridSearchCV** with some preprocessing precisely `Imputer()`
But it looks like during the ForecastingGridSearchCV evaluate method the y pass to the function is not the one preprocessed.

So this is my code :

```python
pipeline=TransformedTargetForecaster(steps=[
                ("imputer", Imputer(method="constant", value=0)),
                ("knn_regressor", NaiveForecaster())]
            )
param_grid={
    "knn_regressor": [make_reduction(KNeighborsRegressor(), strategy="recursive")],
    "knn_regressor__estimator__n_neighbors": np.arange(1, 10, 1)
}
```

```python
y_train, y_test = temporal_train_test_split(estimator.y, test_size=30)

fh = ForecastingHorizon(y_test.index, is_relative=False)

cv = SlidingWindowSplitter(window_length=20)

gs_cv = ForecastingGridSearchCV(
    forecaster=pipeline,
    param_grid=param_grid,
    cv=cv,
    scoring=scorer,
    error_score=error_score,
    refit=refit,
    verbose=verbose,
    n_jobs=n_jobs)
gs_cv.fit(y_train)

y_pred = gs_cv.predict(fh=fh)
```

But I got this error :

```
Traceback (most recent call last):
  File "/Users/nicolas/opt/anaconda3/envs/optalp-commons/lib/python3.8/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/Users/nicolas/opt/anaconda3/envs/optalp-commons/lib/python3.8/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/nicolas/opt/anaconda3/envs/optalp-commons/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/nicolas/opt/anaconda3/envs/optalp-commons/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/Users/nicolas/opt/anaconda3/envs/optalp-commons/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ValueError: Input contains NaN.
```

I debugged the library to try to help you with it, in ```_pipeline/py```when I am on line 960 on ```return self```
values are :
*``` y = demand_quantity [Period                     ] [2020-11-25              NaN] [2020-11-26              NaN] [2020-11-27              NaN] [2020-11-28              NaN] [2020-11-29              NaN] [2020-11-30              NaN] [2020-12-01              NaN] [2020-12-02              NaN] [2020-12-03              NaN] [2020-12-04              NaN] [2020-12-05              NaN] [2020-12-06              NaN] [2020-12-07              NaN] [2020-12-08              NaN] [2020-12-09              NaN] [2020-12-10              NaN] [2020-12-11              NaN] [2020-12-12              NaN] [2020-12-13              NaN] [2020-12-14              NaN]```

* ```yt = demand_quantity [Period                     ] [2020-11-25              0.0] [2020-11-26              0.0] [2020-11-27              0.0] [2020-11-28              0.0] [2020-11-29              0.0] [2020-11-30              0.0] [2020-12-01              0.0] [2020-12-02              0.0] [2020-12-03              0.0] [2020-12-04              0.0] [2020-12-05              0.0] [2020-12-06              0.0] [2020-12-07              0.0] [2020-12-08              0.0] [2020-12-09              0.0] [2020-12-10              0.0] [2020-12-11              0.0] [2020-12-12              0.0] [2020-12-13              0.0] [2020-12-14              0.0]```

* ```t = Imputer(method='constant', value=0)```

* ```self.transformers_pre_ : [('imputer', Imputer(method='constant', value=0))]```
* ```self.transformers_posts_: []```

Then the code code trough and I think the problem will occur there :
```_functions.py``` Line 166-169
```python
        y_pred = eval(pred_type[scitype])(fh, X_test, **metric_args)
        pred_time = time.perf_counter() - start_pred
        # score
        score = scoring(y_test, y_pred, y_train=y_train)
```

Because I have the transformer applied for y_pred but not for y_test
* y_pred : ```demand_quantity [2020-12-15              0.0]```
* y_test : ```demand_quantity [Period                     ] [2020-12-15              NaN]```

On Line 169 precisely scoring method failed and I went to Line 173 to raise the Exception.

It may be not an error from you guys but from me missing some preprocessing to do or else but I hope to get some help on this.

Meanwhile I try a workaround which worked, remove Imputer from pipeline and use Imputer on my entire data then pass my pipeline to **ForecastingGridSearchCV** 

```python

transformer = Imputer(method="constant", value=0)
transformer.fit(estimator.y)
estimator.y = transformer.transform(estimator.y)
estimator.y = estimator.y[-int(len(estimator.y)*0.3):]

y_train, y_test = temporal_train_test_split(estimator.y, test_size=30)

fh = ForecastingHorizon(y_test.index, is_relative=False)

# todo: dynamic cv
cv = SlidingWindowSplitter(window_length=20)

gs_cv = ForecastingGridSearchCV(
    forecaster=pipeline,
    param_grid=param_grid,
    cv=cv,
    scoring=scorer,
    error_score=error_score,
    refit=refit,
    verbose=verbose,
    n_jobs=n_jobs)
gs_cv.fit(y_train)

y_pred = gs_cv.predict(fh=fh)
```

**Comment by fkiraly** [comment]
@Duonijo, this is a very interesting report - I think I understand the underlying issue.
I'm not sure whether this is expected behaviour or not (depending on "specification intention"), but I understand it is a problem at least from the "uninformative error" perspective.

The issue is that if you impute inside the pipeline, the "ground truth" data `y_true` is unchanged, and will contain `nan`-s.
This in turn causes the scorer to fail, because it cannot deal with `nan`-s.

I think from a methodological perspective, you do not actually want to impute the `y_true`, because imputed ground truth biases your evaluation (usually too optimistic).
I think we want the scoring to be able to deal with `nan`-s, e.g., first remove indices with `nan`-s at `y_true`.

I.e., the root cause is about the scorer.

Some workarounds might be:
* pass a scorer that can deal with `nan`-s in `y_true`
* remove indices with `nan`-s from `y`, in the first place (although this may cause other issues)

But I think we may like to extend the scorers to deal with `nan`-s.
Any opinions or further insight?

**Comment by Duonijo** [comment]
Oh ok I think I get it from your explanation.
In my case, I am dealing with industry data where a date is a "demand_date" and value is "demand_quantity". Industries does not save in DB records when there are no demand like this :
```
product: "produc_name" 
demand_date: 2023-30-01
demand_quantity: 0
```

But to forecast the demand over time I sure do have to include days where there are no demands. 

My idea was to preprocess data with `Imputer()` to fill missing days during my series with `Period=daily` with 0 like it should for my whole dataset.
I thought that `Imputer` in `Pipeline` could manage it but like you said `y_true` called y_test on Line 169 still contains `nan`-s values
```python
        score = scoring(y_test, y_pred, y_train=y_train)
```

So I guess it s not a bug ? Maybe a bad practice from me ? In that case what do you suggest me to do ?

I am grateful for your answer.

**Comment by fkiraly** [comment]
> So I guess it s not a bug ? Maybe a bad practice from me ? In that case what do you suggest me to do ?

I'm not quite sure what this is.

- bad practice? I think not, since it's not obvious and the error message is not descriptive.
- a bug? I'm not sure about the logic, but the error message could be improved and considered a bug.

In your application case: do I understand correctly, for you "nan" always means "zero"?
Then you should impute it with 0 before you do anything. Because it's not a "true" nan (data not known/available) but a known zero.

Of course this does not resolve the potential bug, because the data could contain genuine nan.

**Comment by Duonijo** [comment]
Thanks for your answer. I managed it by Imputer my dataset before doing anything on it like you said.

> I'm not quite sure what this is.
>   - bad practice? I think not, since it's not obvious and the error message is not descriptive.
>   - a bug? I'm not sure about the logic, but the error message could be improved and considered a bug.

I mean, it's not a dramatic problem but if there would be a better description of the behavior with the exception raised it will be better I guess.

It's my first post on a Open Source project, idk if I should close myself a ticket ou if it's your role but I am grateful for your serious and the help provided.

**Comment by ngupta23** [comment]
> The issue is that if you impute inside the pipeline, the "ground truth" data y_true is unchanged, and will contain nan-s.
This in turn causes the scorer to fail, because it cannot deal with nan-s.

In pycaret, we had the same issue, but we just use the imputed y_true as that was the best option available at that time. If there is a workaround for it, we can add that option in pycaret as well.

https://github.com/pycaret/pycaret/blob/b6f0eb9bf6b1a36b6756ae9d080bcb81ba909c2a/pycaret/utils/time_series/forecasting/model_selection.py#L143-L147

**Comment by fkiraly** [comment]
> It's my first post on a Open Source project, idk if I should close myself a ticket

Welcome to open source, @duonijo! :-)
and thanks for the very helpful pointer, it highlighted a few things.

The exact protocol varies, but it is fine for the original poster to close the issue if they think it is no longer relevant; or for a maintainer to close the issue if it is solved or otherwise addressed.

In this case, I think it's worth keeping open, until we have addressed the issue with either:

* dealing with nans in error metrics by default
* raising an informative error message in your original use case

**Comment by Duonijo** [comment]
> > The issue is that if you impute inside the pipeline, the "ground truth" data y_true is unchanged, and will contain nan-s.
> > This in turn causes the scorer to fail, because it cannot deal with nan-s.
> 
> In `pycaret`, we had the same issue, but we just use the imputed y_true as that was the best option available at that time. If there is a workaround for it, we can add that option in pycaret as well.
> 
> https://github.com/pycaret/pycaret/blob/b6f0eb9bf6b1a36b6756ae9d080bcb81ba909c2a/pycaret/utils/time_series/forecasting/model_selection.py#L143-L147

@ngupta23 
Indeed I saw your way of doing and I opted for the same solution. 
Your library looks very interesting i should look at it carefully !

@fkiraly 
Thanks a lot, i would be using this library a lot so I think it will be not my last post  :) 
Ok so I leave this ticket open and I guess when a PR fixing this "issue" would be merge to the main branch someone like you will automatically closing up that ticket ?

**Comment by fkiraly** [comment]
>Ok so I leave this ticket open and I guess when a PR fixing this "issue" would be merge to the main branch someone like you will automatically closing up that ticket ?

Exactly!
