### ISSUE TITLE
[BUG] BoxCoxTransformer different behaviour for different shaped input with same data

### ISSUE THREAD

**Issue by jernsting** [sktime/sktime#4410]
**Describe the bug**
When I transform the same input data with the BoxCoxTransformer, I get different outputs.

**To Reproduce**

```python
>>> x_train = np.random.rand(15,1,10)
>>> x_test = np.random.rand(10,1,10)
>>> bct = BoxCoxTransformer().fit(x_train)
>>> bct.transform(x_test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jan/anaconda3/envs/photonai_now/lib/python3.10/site-packages/sktime/transformations/base.py", line 507, in transform
    Xt = self._vectorize("transform", X=X_inner, y=y_inner)
  File "/home/jan/anaconda3/envs/photonai_now/lib/python3.10/site-packages/sktime/transformations/base.py", line 1150, in _vectorize
    raise RuntimeError(
RuntimeError: found different number of instances in transform than in fit. number of instances seen in fit: 15; number of instances seen in transform: 10
>>> bct = BoxCoxTransformer().fit(x_train.squeeze())
>>> bct.transform(x_test.squeeze()
... )
array([[-1.62468952, -0.88374688, -0.36934094, -0.40611213, -0.59917766,
        -0.36873073, -0.06473853, -1.05797497, -0.01144221, -1.27404519],
       [-0.38727403, -0.67076409, -0.47660766, -0.59110494, -0.46152748,
        -1.19813236, -0.44167361, -0.46394852, -0.48259768, -0.68803687],
       [-1.31032562, -0.70404059, -0.71218161, -0.68573268, -0.21862122,
        -0.04041077, -0.28231426, -0.39306662, -0.13347302, -0.76697204],
       [-0.71294509, -0.26468114, -0.28753952, -0.17916924, -0.15026115,
        -0.63208067, -0.43396854, -1.33809091, -0.40796293, -0.07577596],
       [-1.35431907, -0.40291255, -0.91742911, -1.0221456 , -0.00267987,
        -1.20833303, -1.22164845, -0.63812726, -0.56070324, -0.13378569],
       [-0.96676269, -0.18173881, -0.11535683, -0.25441375, -0.57438284,
        -0.46112671, -0.27981984, -1.02279324, -0.39658952, -1.21648491],
       [-0.49292595, -1.0814702 , -0.63032217, -0.12674655, -0.69296646,
        -0.11896896, -0.61602971, -1.63036087, -0.49212753, -1.7917001 ],
       [-1.51386299, -0.06961065, -0.11548332, -0.43097331, -0.56768086,
        -1.64235968, -0.80720475, -0.81043982, -0.56420423, -0.554046  ],
       [-0.08481189, -0.13833271, -0.22677436, -0.35045607, -0.58632054,
        -1.61739332, -0.75869476, -0.12643323, -0.60415908, -0.51813162],
       [-0.0825556 , -0.20488541, -1.00073025, -0.89784301, -0.67953484,
        -0.9634446 , -0.90521541, -0.3464528 , -0.59748565, -0.08256001]])
>>> 

```

**Expected behavior**
I would expect the transformer to output the same data for the non-squeezed input containing one additional dimension. Why does the transformer complain about different number of instances?

**Versions**
<details>

System:
    python: 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0]
executable: /home/jan/anaconda3/envs/****/bin/python
   machine: Linux-5.19.0-35-generic-x86_64-with-glibc2.35

Python dependencies:
          pip: 22.3.1
   setuptools: 65.6.3
      sklearn: 1.1.3
       sktime: 0.16.1
  statsmodels: 0.13.5
        numpy: 1.23.5
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.7.0
       joblib: 1.2.0
        numba: 0.56.4
     pmdarima: 2.0.2
      tsfresh: 0.19.0
</details>

**Comment by jernsting** [comment]
Ok, BoxCox is intended to work on series data. I am filling non-series-data. So I guess this is expected behavior?

**Comment by fkiraly** [comment]
the explanation is, 3D arrays are interpreted (instance, variable, timepoint) by transformers.

The boxcox transformer by default fits a lambda per time series on the training set, so you fit 15 lambdas on your `x_train` (one per instance).

If in the test set you pass 10 series, the estimator does not know which lambda to apply to which of the 10 series - currently an exception is raised if the number of series do not match.

One could question, should there maybe be a different convention, e.g., apply the first 10 lambda that were fitted to the 10 series found in `test`, but currently the implicit assumption is that it is user error if the number does not exactly match. Maybe not the best assumption as said - would lilke to hear your opinion!

**Comment by jernsting** [comment]
This behavior remains confusing to me then. 

Wouldn't it make more sense to learn one lambda per sensor? The number of sensors per instance should remain the same, but for example between training and testing the number of samples or instances can easily changed. Also the order of instances seems to make a difference then?

**Comment by fkiraly** [comment]
well, in your thinking, it is one lambda per subject and sensor, since box-cox lambda estimation is per univariate series (the third dimension, i.e., with python dimension index 2).

In your above example, you train on 15 subjects, with 1 sensor each, so you get 15 times 1 = 15 lambdas.

How would you expect the lambdas to be appied in test, where you have 10 subjects, 1 sensor each? You have 15 lambdas from train, but only 10 series to apply them to.

And, methodologically, applying a lambda from a train subject to a test subject would make sense only if the subjects are identical, at least in the default case.

**Comment by fkiraly** [comment]
ah! I see!

Well, if you want to use if for time series classification, you can wrap it in `FitInTransform`.
This wrapper ensures that the lambda is computed on the same series it is applied to.
Otherwise, the transformer would assume identity between the instances (subjects) in fit and transform.

This is how it would look like:
```python
from sktime.transformations.series.boxcox import BoxCoxTransformer
from sktime.transformations.compose import FitInTransform

boxcox_for_clf = FitInTransform(BoxCoxTransformer())
```
