### ISSUE TITLE
[BUG] TBATS can not produce a forecast with intervals when FH > History Period

### ISSUE THREAD

**Issue by ngupta23** [sktime/sktime#4491]
**Describe the bug**

**To Reproduce**
```python
import numpy as np
import pandas as pd
import logging
from sktime.forecasting.tbats import TBATS


# generate train set values
np.random.seed(42)
LEN_HISTORY = 50
train = pd.Series(data=np.random.randint(1, 100, LEN_HISTORY))

# train model
estimator = TBATS(
    use_box_cox=False,
    use_trend=True,
    use_damped_trend=False,
    sp=10,
    use_arma_errors=False,
)
estimator.fit(train)

# FH = Historical length works!
try:
    fcst1 = estimator.predict_interval(
        coverage=0.8, fh=np.array(range(1, LEN_HISTORY + 1))
    )
except Exception as e:
    print("FH <= History")
    logging.exception(e)

# FH > Historical length DOES NOT work
try:
    fcst2 = estimator.predict_interval(
        coverage=0.8, fh=np.array(range(1, LEN_HISTORY + 2))
    )
except Exception as e:
    print("FH > History")
    logging.exception(e)
```

```python-traceback
FH > History
ERROR:root:Length mismatch: Expected axis has 1 elements, new values have 51 elements
Traceback (most recent call last):
  File "analysis/tbats/TBATS_prediction_interval_issue.py", line 34, in <module>
    coverage=0.8, fh=np.array(range(1, LEN_HISTORY + 2))
  File "/home/<hidden>/anaconda3/envs/<hidden>/lib/<hidden>/site-packages/sktime/forecasting/base/_base.py", line 636, in predict_interval
    pred_int = self._predict_interval(fh=fh, X=X_inner, coverage=coverage)
  File "/home/<hidden>/anaconda3/envs/<hidden>/lib/<hidden>/site-packages/sktime/forecasting/base/adapters/_tbats.py", line 293, in _predict_interval
    _, tbats_pred_int = self._tbats_forecast_with_interval(fh, c)
  File "/home/<hidden>/anaconda3/envs/<hidden>/lib/<hidden>/site-packages/sktime/forecasting/base/adapters/_tbats.py", line 217, in _tbats_forecast_with_interval
    pred_int = self._get_pred_int(lower=lower, upper=upper)
  File "/home/<hidden>/anaconda3/envs/<hidden>/lib/<hidden>/site-packages/sktime/forecasting/base/adapters/_tbats.py", line 345, in _get_pred_int
    pred_int.index = fh_out.to_absolute(self.cutoff)
  File "/home/<hidden>/anaconda3/envs/<hidden>/lib/<hidden>/site-packages/pandas/core/generic.py", line 5154, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "/home/<hidden>/anaconda3/envs/<hidden>/lib/<hidden>/site-packages/pandas/core/generic.py", line 564, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/<hidden>/anaconda3/envs/<hidden>/lib/<hidden>/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 1 elements, new values have 51 elements
```

**Expected behavior**
Requesting Prediction Intervals should work when FH > len(history) since it works when just requesting predictions without intervals (so it there should not be a historical data insufficiency issue).

**Versions**
<details>
sktime 0.16.0 and sktime 0.17.0
</details>

**Comment by fkiraly** [comment]
FYI @yarnabrina,this looks similar to code you are currently refactoring for `statsmodels`.
This seems to come from `fh`, have you encountered this before?

**Comment by fkiraly** [comment]
update: not coming from `fh`, that is fine.
It is coming from preceding code, which produces `pred_int` of wrong length, as soon as the prediction index exceeds length of the previous series.
