### ISSUE TITLE
[BUG] Time series DBSCAN crashes on str distance key

### ISSUE THREAD

**Issue by IagoMG** [sktime/sktime#4697]
**Describe the bug**
I have a numpy array of size (1560, 2) where column 0 is integer data and column 1 is time data in unix format.
So when I try to use the .fit(array) method, it gives the following output:

```
T>>> tsdbscan = TimeSeriesDBSCAN('euclidean')
>>> tsdbscan.fit(X)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/env/lib/python3.11/site-packages/sktime/clustering/base.py", line 119, in fit
    self._fit(X)
  File "/tmp/env/lib/python3.11/site-packages/sktime/clustering/dbscan.py", line 124, in _fit
    distmat = distance(X)
              ^^^^^^^^^^^
TypeError: 'str' object is not callable
```

**To Reproduce**

```python
from sktime.clustering.dbscan import TimeSeriesDBSCAN as TSDBSCAN

X = np.random.randint(0, 100, (100, 2))

tsdbscan = TSDBSCAN(distance='dwt')
tsdbscan.fit(X)
```

**Expected behavior**
Expecting to work with distance as str.

**Additional context**

**Versions**
0.19.1

**Comment by achieveordie** [comment]
Looking at the source code, in the current state, `TSDBSCAN` only supports callable and not strings. This is not the appropriate behaviour as the docstring mentions that strings can be used for distance calculation.

If @hazrulakmal isn't looking into it yet (tagging you since you left a thumbs up), let me fix it.

**Comment by fkiraly** [comment]
yes, indeed, @achieveordie, that agrees with my diagnosis.

The docstring and the code do not agree - but str should of course be supported.

I thought a quick fix might be, factor out the "resolve str to estimator" logic from, say `KNeighborsTimeSeriesClassifier`. Not sure about the bets form, I would give it two possible output types - a callable np3D x np3D -> np2D; and a pairwise panel transformer (from `distances`).

That is, sth like `_resolve_str_distance`, which then can be called in a `_check_distance` that lets estimators or callables pass, and resolves str to estimators or callables.

This can then be called in any estimator that allows str arg for distances
