### ISSUE TITLE
[BUG] make_reduction with strategies 'direct' and 'dirrec' and models 'update' don't work  as expected

### ISSUE THREAD

**Issue by corradomio** [sktime/sktime#4844]
We suppose to have a dataset `D=(X,y)`, subdivided in train and test:

1. train: `Dt = (fht, Xt, yt)`
2. test:  `Ds = (fhs, Xs, ys)`

with `D=Dt|Ds` (concatenation, with timestamps in order)
(`fh?` is the 'timestamp' attached to each record)

The strategy `direct` requires to train the model using:

```
model.fit(y=yt,X=Xt,fh=fhs)
```
then, it is possible to predict ONLY `fhs`:

```
y_pred = model.predict(fh=fhs, X=Xs)
```

Now, I like update the model with the information available in the test dataset. Because the fit needs the forecasting horizon, IN THEORY I can use the SAME RELATIVE horizon for the update.

HERE there is the problem:
If I call

```
model.update(y=ys, X=Xs)
```

it is generated the exception

```
Traceback (most recent call last):
  File "D:\Dropbox\Projects\Projects.ebtic\ipredict.v4.5\src\ipredict\ipredict.py", line 339, in fit
    self._model_update(model_name, model, fh_update, y_test_, X_test_)
  File "D:\Dropbox\Projects\Projects.ebtic\ipredict.v4.5\src\ipredict\ipredict.py", line 397, in _model_update
    model.update(y=y_update, X=X_update)
  File "D:\Python\Anaconda3-2022.05\envs\ipredict\lib\site-packages\sktime\forecasting\base\_base.py", line 842, in update
    self._update(y=y_inner, X=X_inner, update_params=update_params)
  File "D:\Python\Anaconda3-2022.05\envs\ipredict\lib\site-packages\sktime\forecasting\base\_base.py", line 1878, in _update
    self.fit(y=self._y, X=self._X, fh=self._fh)
  File "D:\Python\Anaconda3-2022.05\envs\ipredict\lib\site-packages\sktime\forecasting\base\_base.py", line 348, in fit
    self._fit(y=y_inner, X=X_inner, fh=fh)
  File "D:\Dropbox\Projects\Projects.ebtic\ipredict.v4.5\src\ipredict\sktimex\scikit_model.py", line 135, in _fit
    self.forecaster.fit(y=y, X=X, fh=fh)
  File "D:\Python\Anaconda3-2022.05\envs\ipredict\lib\site-packages\sktime\forecasting\base\_base.py", line 348, in fit
    self._fit(y=y_inner, X=X_inner, fh=fh)
  File "D:\Python\Anaconda3-2022.05\envs\ipredict\lib\site-packages\sktime\forecasting\compose\_reduce.py", line 510, in _fit
    raise NotImplementedError("In-sample predictions are not implemented.")
NotImplementedError: In-sample predictions are not implemented.
```

IF I use

```
model.update(y=ys, X=Xs, fh=fhs)
```

it is generated the exception

```
Traceback (most recent call last):
  File "D:\Dropbox\Projects\Projects.ebtic\ipredict.v4.5\src\ipredict\ipredict.py", line 339, in fit
    self._model_update(model_name, model, fh_update, y_test_, X_test_)
  File "D:\Dropbox\Projects\Projects.ebtic\ipredict.v4.5\src\ipredict\ipredict.py", line 396, in _model_update
    model.update(y=y_update, X=X_update, fh=fh_update)
TypeError: update() got an unexpected keyword argument 'fh'
```

--------------

It seems that to use a tabular model with "direct/dirrec" strategy to predict "future values" it is very intricate.

**Comment by Famous077** [comment]
Hi @corradomio ,I’d like to look into this issue around updating direct/dirrec forecasters and the errors raised during `update`. I can investigate the behaviour and propose a fix or clarification. Could you assign this to me?
