### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by whoknowsB** [sktime/sktime#4885]
**Describe the bug**
Splitters miss a fold at the end: 

**To Reproduce**

```python
import pandas as pd
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sktime.utils.plotting import plot_windows

temp = pd.DataFrame({
    'y': range(7*24),
    'objectid': [1] * 7 * 24,
    'timestamp': pd.date_range('2022-07-01 00:00:00', '2022-07-7 23:00:00', freq='H')
}).set_index(['objectid', 'timestamp'])


fh = pd.timedelta_range(start=0, end=pd.Timedelta(days=1), closed='right', freq='H')
initial_window = pd.Timedelta(days=1)
step_length = pd.Timedelta(days=1)
splitter = ExpandingWindowSplitter(fh=fh, initial_window=initial_window, step_length=step_length)

plot_windows(splitter, temp)
```

**Expected behavior**
The output number of splits is 5, it should be 6

**Additional context**
<img width="1321" alt="image" src="https://github.com/sktime/sktime/assets/12576795/2fa87e4c-a137-49d1-aa4e-cfbedfda807e">

**Versions**
'0.20.0'

</details>

**Comment by fkiraly** [comment]
Yes, this looks incorrect. My immediate suspicion is that it has to do with inconsistent handling of `pandas` of time-like and integer-like indexing, i.e., `x[:end]` including `end` for time-like and excluding `end` for integer-like.

What would be helpful is checking if the same problem happens for integer-based index, and generating a code vignette for versus debugging.

**Comment by fkiraly** [comment]
Confirmed on windows, current `main`, python 3.10.

**Comment by fkiraly** [comment]
FYI @hazrulakmal, @benHeid, @benshamza (recently looked into splitters)

**Comment by whoknowsB** [comment]
Integer base index is indeed correct:

```python
import pandas as pd
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sktime.utils.plotting import plot_windows

temp = pd.DataFrame({
    'y': range(7*24),
    'objectid': [1] * 7 * 24,
    'timestamp': range(7*24)
}).set_index(['objectid', 'timestamp'])


fh = range(1,25)
initial_window = 24
step_length = 24
splitter = ExpandingWindowSplitter(fh=fh, initial_window=initial_window, step_length=step_length)

plot_windows(splitter, temp)
```

<img width="1321" alt="image" src="https://github.com/sktime/sktime/assets/12576795/f5c2b92a-54c6-415e-bd9b-6eaf38471168">

**Comment by fkiraly** [comment]
Update: not sure yet as there is really a lot of nesting going on...

But it'd most likely localized in `BaseWindowSplitter.get_cutoffs`.

Returns `[ 24  48  72  96 120]` in timedelta case, `[ 24  48  72  96 120 144]` in int case.

**Comment by fkiraly** [comment]
Update: the problem is in the logic in these lines, which computes the blue/orange cut points:

```python
            start_date = y[y < y[start] + offset][-1]
            end_date = y[end - 1] - step_length if end <= len(y) else y[-1]
            date_cutoffs = pd.date_range(
                start=start_date, end=end_date, freq=step_length
            )
```
(line 1024 following in `forecasting.model_selection._split`)

I don't quite get why it's doing what it's doing and am tempted to simply rewrite it from scratch.

I'll have to work on the release now and will leave this over the weekend, but if someone else gets it, a PR is welcome.

**Comment by whoknowsB** [comment]
it looks like
```python
end_date = y[end - 1] - step_length if end <= len(y) else y[-1]
```
takes the end and subtracts step_length, thus giving one time windows less
```python
end_date = y[end - 1] if end <= len(y) else y[-1]
```
should do the job done :)


https://github.com/sktime/sktime/blob/0c8b8a15cfe63922742adbbb66717712aaaf3d0a/sktime/forecasting/model_selection/_split.py#L1025C1-L1025C1

**Comment by fkiraly** [comment]
I'll try this out and see whether it fixes it.

> I'm not that familiar with the PR for this library, so other eyes may help

Works like PR to any GitHub repository - let us know if you want to try this and become a contributor! In the discord dev-chat channel, happy to help if you get stuch.
You can already get the `bug` badge for the report and proposed fix.

http://www.sktime.net/en/latest/get_involved/contributing.html
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request-from-github-desktop

**Comment by fkiraly** [comment]
Copied the fix here:
https://github.com/sktime/sktime/pull/4886

and included a test based on your vignettes (you are credited as co-contributor on this).

The test is still failing as `get_n_splits` does not seem to work.

Feel free to take this over, e.g., by branching off and making a PR.

I suppose, from a general standpoint, we need to test all the splitters much more stringently for time based indices.

**Comment by hazrulakmal** [comment]
@fkiraly just wondering how did you manage to get `.get_cutoffs` return of the following:

> Returns` [ 24  48  72  96 120] in timedelta case, [ 24  48  72  96 120 144] in int case.

Because, I tried to get the them too by running the following line but it ran into a `TypeError` of the following

```python
splitter.get_cutoffs(temp)
```
Traceback
<details>
Traceback (most recent call last):

File "c:\Users\hazru\Desktop\github\sktime\sktime\_contrib\temp\test-forecastingcv.py", line 26, in <module>
splitter.get_cutoffs(temp)
File "C:\Users\hazru\Desktop\github\sktime\sktime\forecasting\model_selection\_split.py", line 1020, in get_cutoffs
start = self._get_start(y=y, fh=fh)
File "C:\Users\hazru\Desktop\github\sktime\sktime\forecasting\model_selection\_split.py", line 963, in _get_start
start = y.get_loc(y[start] + self.window_length)
TypeError: can only concatenate tuple (not "Timedelta") to tuple
</details>

**Comment by fkiraly** [comment]
Hm, I thought like that? Or maybe in the debugger?

Either way, the fix in #4886 seemed to be working and then some dependency might have changed (`pandas`) and I don't understand why it's no longer passing tests.
