### ISSUE TITLE
[BUG] `mean_absolute_scaled_error` has `y_train` as a mandatory keyword argument which is not part of function signature

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#4974]
This is the function definition of MASE:

```python3
def mean_absolute_scaled_error(
    y_true, y_pred, sp=1, horizon_weight=None, multioutput="uniform_average", **kwargs
):
```

Based on this, passing `y_true` and `y_pred` should be sufficient. However, that fails complaining this:

```pycon
>>> from sktime.performance_metrics.forecasting import mean_absolute_scaled_error
>>> mean_absolute_scaled_error([1, 2, 3], [6, 5, 4])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anirban/sktime-fork/sktime/performance_metrics/forecasting/_functions.py", line 415, in mean_absolute_scaled_error
    y_train = _get_kwarg("y_train", metric_name="mean_absolute_scaled_error", **kwargs)
  File "/home/anirban/sktime-fork/sktime/performance_metrics/forecasting/_functions.py", line 60, in _get_kwarg
    raise ValueError(msg)
ValueError: mean_absolute_scaled_error requires `y_train`. Pass `y_train` as a keyword argument when calling the metric.
```

It is also not mentioned in the [documentation](https://www.sktime.net/en/stable/api_reference/auto_generated/sktime.performance_metrics.forecasting.mean_absolute_scaled_error.html) that `y_train` must be passed.

Suggestions:

1. document that `y_train` is mandatory
2. make `y_train` part of function signature
3. make mandatory keyword arguments positional
4. similar changes for other metrics

**Comment by fkiraly** [comment]
1. agreed
2 + 3 + 4. I think there is a subtle problem of this. The metrics need to follow a strategy pattern of "same signature" to plug in to the various dependencies, such as tuning. Unfortunately, `y_train` now always comes after any actual and potential parameters such as `sp`, so turning `y_train` into a named arg would be a breaking change, either for the signature, or the strategy pattern. I don't know how to solve this

To the metric classes, if this doesn't already exist, I would add tags that indicate which of the arguments are necessary.
