### ISSUE TITLE
Error while tuning the hyperparameters

### ISSUE THREAD

**Issue by jijo7** [sktime/sktime#5158]
Hi
The length of my monthly dataset is 387. Specifically, I plan to divide the data as follows: the first 351 observations will constitute the training data, observations 352 to 375 will form the validation set, and observations 376 to 387 will be designated as the test set. Within this context, I have identified the variable "23357" as the target series that needs to be predicted, while the variables "10066" and "21986" will serve as independent or exogenous variables. Moreover, I am interested in utilizing the lagged values of the variable "23357" in the model, specifically incorporating the first through sixth lags.

For the prediction task, I intend to utilize an expanding window approach, forecasting the upcoming step or month – essentially performing one-step-ahead predictions. Given that my validation set encompasses 24 observations, it will necessitate re-fitting the model 24 times to facilitate accurate predictions. Following the hyperparameter tuning process, my ultimate objective is to forecast the outcomes for the final 12 observations.

To achieve these goals, I've composed the following code:
[data.csv](https://github.com/sktime/sktime/files/12424943/data.csv)

```
import pandas as pd
import numpy as np
from sktime.forecasting.model_selection import temporal_train_test_split
import optuna
from hyperopt import STATUS_OK,Trials,fmin,hp,tpe
from xgboost import XGBRegressor
from sklearn.metrics import log_loss, accuracy_score, mean_absolute_error, r2_score
from optuna.integration import XGBoostPruningCallback
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sktime.forecasting.base import ForecastingHorizon
from scipy.stats import kruskal
from statsmodels.tsa.stattools import adfuller
import pymannkendall as mk
from sktime.forecasting.compose import ForecastingPipeline
from sktime.transformations.compose import ColumnwiseTransformer
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.transformations.series.boxcox import LogTransformer
from sktime.forecasting.compose import make_reduction
from sktime.forecasting.model_selection import ForecastingGridSearchCV, ForecastingRandomizedSearchCV
from sktime.performance_metrics.forecasting import (MeanAbsolutePercentageError as MAPE,
                                                    MeanAbsolutePercentageError)
MAPE = MeanAbsolutePercentageError()

# Read the CSV file
df = pd.read_csv("data.csv", index_col=0, parse_dates=True) 
# Rename index to "DateTime"
df.index.rename("Date", inplace=True)
# Convert the index to datetime type
df.index = pd.to_datetime(df.index).date


# Divide data into train and test
train_df, test_df = temporal_train_test_split(df, test_size = 12)

train_df.index = pd.to_datetime(train_df.index)
test_df.index = pd.to_datetime(test_df.index)

# Exogenous variables
columns_to_keep= train_df.columns.difference(["23357"])
cols_for_log_transform = list(columns_to_keep)

# Initial window is train data - validation data
in_win = len(train_df)-2*len(test_df) 

# Assuming the indices 351 to 375 from train_df are validation set
start_idx = 351
end_idx = 375
fh = ForecastingHorizon(train_df.index[start_idx:end_idx + 1], is_relative=False)

# Tuning hyperparameters using grid search
params = {
    "forecaster__forecast__estimator__objective": ["reg:squarederror"],
    "forecaster__forecast__estimator__eval_metric": ["mape"],
    "forecaster__forecast__estimator__use_label_encoder": [False],
    "forecaster__forecast__estimator__n_estimators": [100, 200],
    "forecaster__forecast__estimator__learning_rate": [0.1, 0.08, 0.05],
    "forecaster__forecast__estimator__random_state":[42],
    "forecaster__forecast__estimator__min_child_weight": [256],
        }
pipe = ForecastingPipeline(
    steps=[
        ("price_column_transformer", ColumnwiseTransformer(LogTransformer(), columns=cols_for_log_transform)),
        (
            "forecaster",
            TransformedTargetForecaster(
                [
                    ("LogTransformer", LogTransformer()),
                    (
                        "forecast",
                        make_reduction(
                            XGBRegressor(**params
                                
                            ),
                            window_length=1,
                            strategy="direct"
                            
                        ),
                    ),
                ]
            ),
        ),
    ]
)

cv = ExpandingWindowSplitter(step_length=1, initial_window=in_win, fh=24)

gscv = ForecastingGridSearchCV(
    forecaster=pipe,
    param_grid= params,
    cv=cv,
    n_jobs=-1,
)
gscv.fit(train_df[["23357"]], train_df[columns_to_keep],fh=fh)
gscv.best_params_
```

However, I am encountering the following error:

```
NotFittedError                            Traceback (most recent call last)
[<ipython-input-37-326b9742b016>](https://localhost:8080/#) in <cell line: 55>()
     53     n_jobs=-1,
     54 )
---> 55 gscv.fit(train_df[["23357"]], train_df[columns_to_keep],fh=fh)
     56 gscv.best_params_

1 frames
[/usr/local/lib/python3.10/dist-packages/sktime/forecasting/model_selection/_tune.py](https://localhost:8080/#) in _fit(self, y, X, fh)
    233         # Raise error if all fits in evaluate failed because all score values are NaN.
    234         if self.best_index_ == -1:
--> 235             raise NotFittedError(
    236                 f"""All fits of forecaster failed,
    237                 set error_score='raise' to see the exceptions.

NotFittedError: All fits of forecaster failed,
                set error_score='raise' to see the exceptions.
                Failed forecaster: ForecastingPipeline(steps=[('price_column_transformer',
                            ColumnwiseTransformer(columns=['10066', '21986'],
                                                  transformer=LogTransformer())),
                           ('forecaster',
                            TransformedTargetForecaster(steps=[('LogTransformer',
                                                                LogTransformer()),
                                                               ('forecast',
                                                                DirectTabularRegressionForecaster(estimator=XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=...
             forecaster__forecast__estimator__random_state=[42],
             forecaster__forecast__estimator__use_label_encoder=[False],
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, ...),
                                                                                                  window_length=1))]))])
```
Note:  the same error persists when attempting to execute the final section of[ this code](https://towardsdatascience.com/build-complex-time-series-regression-pipelines-with-sktime-910bc25c96b6), where `ForecastingRandomizedSearchCV` is being employed.

I also made an attempt to employ `Optuna `for the purpose of hyperparameter tuning, as demonstrated below:

```
def objective(trial):
  # Params
  params = {
        "objective": trial.suggest_categorical('objective', ["reg:squarederror"]),
        "eval_metric": trial.suggest_categorical('eval_metric', ["mape"]),
        "use_label_encoder": trial.suggest_categorical('use_label_encoder', [False]),
        "n_estimators": trial.suggest_categorical('n_estimators', [40000]),
        "learning_rate": trial.suggest_float('learning_rate', 0.15, 1.0, log=True),
        "subsample": trial.suggest_float('subsample', 0.1, 1, step=0.01),
        "colsample_bytree": trial.suggest_float('colsample_bytree', 0.05, 1, step=0.01),
        "max_depth": trial.suggest_int("max_depth", 1, 8),
        "booster": trial.suggest_categorical('booster', ["gbtree"]),
        "gamma": trial.suggest_float('gamma', 0, 100, step=0.1),
        "reg_lambda": trial.suggest_float('reg_lambda', 0.1, 100, log=True),
        "reg_alpha": trial.suggest_float('reg_alpha', 0.1, 100, log=True),
        "random_state": trial.suggest_categorical('random_state', [42]),
        "n_jobs": trial.suggest_categorical('n_jobs', [4]),
        "min_child_weight": trial.suggest_categorical("min_child_weight", [256]),
            }
  pipe = ForecastingPipeline(
        steps=[
            ("price_column_transformer", ColumnwiseTransformer(LogTransformer(), columns=cols_for_log_transform)),
            (
                "forecaster",
                TransformedTargetForecaster(
                    [
                        ("LogTransformer", LogTransformer()),
                        (
                            "forecast",
                            make_reduction(
                                XGBRegressor(**params
                                ),
                                window_length=1,
                                strategy="direct",
                            ),
                        ),
                    ]
                ),
            ),
        ]
    )
  splitter = ExpandingWindowSplitter(step_length=1, initial_window=in_win, fh=1)
  cv = splitter.split(train_df)

  errors = []
  columns_to_keep= train_df.columns.difference(["23357"])
  for train, test in cv:
    fh = ForecastingHorizon(train_df.index[test], is_relative=False)
    pipe.fit(train_df[["23357"]].iloc[train], train_df[columns_to_keep].iloc[train],fh=1)
    yhat = pipe.predict(train_df[columns_to_keep].iloc[test],fh)
    errors.append(MAPE(train_df[["23357"]].iloc[test], yhat))

    return np.mean(errors)

# Create study
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=2)
print(study.best_params)

print("Best value: {:.5f}".format(study.best_value))
print("Best params:")

for key, value in study.best_params.items():
    print("{}: {}".format(key, value))

params = trial.params
model = XGBRegressor(**params)
model.fit(train_df[columns_to_keep], train_df[["23357"]])

y_pred = model.predict(test_df[columns_to_keep])
mape = MAPE(test_df[["23357"]], y_pred)
print("MAPE after tuning: %.2f%%" % (mape * 100.0))
```

Regrettably, an additional error message is being raised.

```
[I 2023-08-23 22:30:11,271] A new study created in memory with name: no-name-ac3843d6-4798-43b7-9e3b-6f275632a31e
[W 2023-08-23 22:30:23,421] Trial 0 failed with parameters: {'objective': 'reg:squarederror', 'eval_metric': 'mape', 'use_label_encoder': False, 'n_estimators': 40000, 'learning_rate': 0.3869839760229869, 'subsample': 0.13, 'colsample_bytree': 0.7000000000000001, 'max_depth': 1, 'booster': 'gbtree', 'gamma': 10.5, 'reg_lambda': 92.71023987279064, 'reg_alpha': 10.945335354492544, 'random_state': 42, 'n_jobs': 4, 'min_child_weight': 256} because of the following error: TypeError("Invalid `fh`. The type of the passed `fh` values is not supported. Please use one of ('int', 'range', '1D np.ndarray of type int', '1D np.ndarray of type timedelta or dateoffset', 'list of type int', 'pd.RangeIndex', 'pd.PeriodIndex', 'pd.DatetimeIndex', 'pd.TimedeltaIndex'), but found type <class 'pandas.core.frame.DataFrame'>, values =                10066     21986\n2020-04-01  317.4375  164.4375").
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-39-e50ad275d5c6>", line 57, in objective
    yhat = pipe.predict(train_df[columns_to_keep].iloc[test],fh)
  File "/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/_base.py", line 397, in predict
    fh = self._check_fh(fh)
  File "/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/_base.py", line 1749, in _check_fh
    fh = check_fh(fh=fh, freq=self._cutoff)
  File "/usr/local/lib/python3.10/dist-packages/sktime/utils/validation/forecasting.py", line 291, in check_fh
    fh = ForecastingHorizon(fh, is_relative=None, freq=freq)
  File "/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/_fh.py", line 296, in __init__
    values = _check_values(values)
  File "/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/_fh.py", line 134, in _check_values
    raise TypeError(
TypeError: Invalid `fh`. The type of the passed `fh` values is not supported. Please use one of ('int', 'range', '1D np.ndarray of type int', '1D np.ndarray of type timedelta or dateoffset', 'list of type int', 'pd.RangeIndex', 'pd.PeriodIndex', 'pd.DatetimeIndex', 'pd.TimedeltaIndex'), but found type <class 'pandas.core.frame.DataFrame'>, values =                10066     21986
2020-04-01  317.4375  164.4375
[W 2023-08-23 22:30:23,422] Trial 0 failed with value None.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-39-e50ad275d5c6>](https://localhost:8080/#) in <cell line: 64>()
     62 # Rest of your code remains unchanged
     63 study = optuna.create_study(direction="minimize")
---> 64 study.optimize(objective, n_trials=2)
     65 print(study.best_params)

10 frames
[/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/_fh.py](https://localhost:8080/#) in _check_values(values)
    132             *[f"pd.{index_type.__name__}" for index_type in VALID_INDEX_TYPES],
    133         )
--> 134         raise TypeError(
    135             f"Invalid `fh`. The type of the passed `fh` values is not supported. "
    136             f"Please use one of {valid_types}, but found type {type(values)}, "

TypeError: Invalid `fh`. The type of the passed `fh` values is not supported. Please use one of ('int', 'range', '1D np.ndarray of type int', '1D np.ndarray of type timedelta or dateoffset', 'list of type int', 'pd.RangeIndex', 'pd.PeriodIndex', 'pd.DatetimeIndex', 'pd.TimedeltaIndex'), but found type <class 'pandas.core.frame.DataFrame'>, values =                10066     21986
2020-04-01  317.4375  164.4375

```
I would greatly appreciate your assistance in resolving these errors. Your guidance in addressing these issues would be highly valuable.

**Comment by fkiraly** [comment]
Thanks for reporting!

Would it be possible for you to turn this into some code that does not rely on a data import? That makes it much harder to use.

That is, can you make the problem appear with data constructed in memory, e.g., using one of the `sktime` toy datasets, or the `pd.DataFrame` constructor?

**Comment by jijo7** [comment]
First, many thanks for your time and consideration. Then, the following code reproduce the errors: 

```
# Generate a list of dates from 1991-01-01 to 2023-03-01
date_range = pd.date_range(start="1991-01-01", end="2023-03-01", freq="MS")

# Create random values for columns 10066, 21986, and 23357
num_rows = len(date_range)
values_10066 = np.random.rand(num_rows) * 1000
values_21986 = np.random.rand(num_rows) * 500
values_23357 = np.random.rand(num_rows) * 50

# Create a dictionary with column names and corresponding values
data = {
    "10066": values_10066,
    "21986": values_21986,
    "23357": values_23357
}

# Create the DataFrame
df = pd.DataFrame(data, index=date_range)
```

**Comment by jijo7** [comment]
However, this code works well: 
```
from sktime.datasets import load_airline
y = load_airline()
import numpy as np
import pandas as pd
from sktime.forecasting.model_selection import temporal_train_test_split, SingleWindowSplitter, ForecastingRandomizedSearchCV
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.compose import make_reduction, TransformedTargetForecaster
from sktime.utils.plotting import plot_series
from sktime.performance_metrics.forecasting import mean_absolute_percentage_error
from sktime.transformations.series.detrend import Deseasonalizer, Detrender
from sktime.forecasting.trend import PolynomialTrendForecaster
	
from xgboost import XGBRegressor

from statsmodels.tsa.seasonal import seasonal_decompose

# Create an exogenous dataframe indicating the month
X = pd.DataFrame({'month': y.index.month}, index=y.index)
X = pd.get_dummies(X.astype(str), drop_first=True)

# Split data
y_train, y_test = temporal_train_test_split(y, test_size=26) # Predict from 1st July 2019
X_train, X_test = temporal_train_test_split(X, test_size=26)


# Forecasting horizon, same as test data
fh = ForecastingHorizon(y_test.index, is_relative=False)

# Window for cross-validation
validation_size = 26
cv = SingleWindowSplitter(window_length=len(y)-validation_size, fh=validation_size)

# XGBoost forecaster with grid of parameters and detrender and deseasonaliser
regressor = XGBRegressor(objective='reg:squarederror', random_state=42)
forecaster = TransformedTargetForecaster(
    [
        ("deseasonalize", Deseasonalizer(model="multiplicative", sp=12)),
        ("detrend", Detrender(forecaster=PolynomialTrendForecaster(degree=1))),
        ("forecast", make_reduction(regressor, window_length=52, strategy="recursive"),
        ),
    ]
)

# Param grid
param_grid = {
    'deseasonalize__model': ['multiplicative', 'additive'],
    'detrend__forecaster__degree': [1, 2, 3],
    'forecast__estimator__max_depth': [3, 5, 6, 10, 15, 20],
    'forecast__estimator__learning_rate': [0.01, 0.1, 0.2, 0.3],
    'forecast__estimator__subsample': np.arange(0.5, 1.0, 0.1),
    'forecast__estimator__colsample_bytree': np.arange(0.4, 1.0, 0.1),
    'forecast__estimator__colsample_bylevel': np.arange(0.4, 1.0, 0.1),
    'forecast__estimator__n_estimators': [100, 500, 1000]
}

# Randomised search
gscv = ForecastingRandomizedSearchCV(forecaster, cv=cv, param_distributions=param_grid, n_iter=100, random_state=42)

# Fit and predict
gscv.fit(y=y_train, X=X_train)
y_pred = gscv.predict(fh=fh, X=X_test)

# Evaluate
print('MAPE: %.4f' % mean_absolute_percentage_error(y_test, y_pred, symmetric=False))
```

**Comment by fkiraly** [comment]
Thanks - I'll copy the two pieces of code together for easy checking:

```python
import pandas as pd
import numpy as np
from sktime.forecasting.model_selection import temporal_train_test_split
import optuna
from hyperopt import STATUS_OK,Trials,fmin,hp,tpe
from xgboost import XGBRegressor
from sklearn.metrics import log_loss, accuracy_score, mean_absolute_error, r2_score
from optuna.integration import XGBoostPruningCallback
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from sktime.forecasting.base import ForecastingHorizon
from scipy.stats import kruskal
from statsmodels.tsa.stattools import adfuller
import pymannkendall as mk
from sktime.forecasting.compose import ForecastingPipeline
from sktime.transformations.compose import ColumnwiseTransformer
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.transformations.series.boxcox import LogTransformer
from sktime.forecasting.compose import make_reduction
from sktime.forecasting.model_selection import ForecastingGridSearchCV, ForecastingRandomizedSearchCV
from sktime.performance_metrics.forecasting import (MeanAbsolutePercentageError as MAPE,
                                                    MeanAbsolutePercentageError)
MAPE = MeanAbsolutePercentageError()

# Generate a list of dates from 1991-01-01 to 2023-03-01
date_range = pd.date_range(start="1991-01-01", end="2023-03-01", freq="MS")

# Create random values for columns 10066, 21986, and 23357
num_rows = len(date_range)
values_10066 = np.random.rand(num_rows) * 1000
values_21986 = np.random.rand(num_rows) * 500
values_23357 = np.random.rand(num_rows) * 50

# Create a dictionary with column names and corresponding values
data = {
    "10066": values_10066,
    "21986": values_21986,
    "23357": values_23357
}

# Create the DataFrame
df = pd.DataFrame(data, index=date_range)

# Divide data into train and test
train_df, test_df = temporal_train_test_split(df, test_size = 12)

train_df.index = pd.to_datetime(train_df.index)
test_df.index = pd.to_datetime(test_df.index)

# Exogenous variables
columns_to_keep= train_df.columns.difference(["23357"])
cols_for_log_transform = list(columns_to_keep)

# Initial window is train data - validation data
in_win = len(train_df)-2*len(test_df) 

# Assuming the indices 351 to 375 from train_df are validation set
start_idx = 351
end_idx = 375
fh = ForecastingHorizon(train_df.index[start_idx:end_idx + 1], is_relative=False)

# Tuning hyperparameters using grid search
params = {
    "forecaster__forecast__estimator__objective": ["reg:squarederror"],
    "forecaster__forecast__estimator__eval_metric": ["mape"],
    "forecaster__forecast__estimator__use_label_encoder": [False],
    "forecaster__forecast__estimator__n_estimators": [100, 200],
    "forecaster__forecast__estimator__learning_rate": [0.1, 0.08, 0.05],
    "forecaster__forecast__estimator__random_state":[42],
    "forecaster__forecast__estimator__min_child_weight": [256],
        }
pipe = ForecastingPipeline(
    steps=[
        ("price_column_transformer", ColumnwiseTransformer(LogTransformer(), columns=cols_for_log_transform)),
        (
            "forecaster",
            TransformedTargetForecaster(
                [
                    ("LogTransformer", LogTransformer()),
                    (
                        "forecast",
                        make_reduction(
                            XGBRegressor(**params
                                
                            ),
                            window_length=1,
                            strategy="direct"
                            
                        ),
                    ),
                ]
            ),
        ),
    ]
)

cv = ExpandingWindowSplitter(step_length=1, initial_window=in_win, fh=24)

gscv = ForecastingGridSearchCV(
    forecaster=pipe,
    param_grid= params,
    cv=cv,
    n_jobs=-1,
)
gscv.fit(train_df[["23357"]], train_df[columns_to_keep],fh=fh)
gscv.best_params_
```

**Comment by fkiraly** [comment]
@jijo7, I tried to replace the XGBoost dependency by a `LinearRegressor`, and I get a different error - `All fits of forecaster failed`

**Comment by fkiraly** [comment]
Sth is going on here, but I don't get the same thing - FYI @benHeid, @yarnabrina, something with the `ForecastingHorizon` seems to be going on.

**Comment by yarnabrina** [comment]
The error looks identical to #5131.

**Comment by fkiraly** [comment]
> The error looks identical to https://github.com/sktime/sktime/issues/5131.

Oh, is it?
There's a lot of code, so I did not boil it down to the root cause.

If this looks like someone else is also having the problem, we should raise the priority on trying to find a solution.
