### ISSUE TITLE
[BUG] - MatrixProfileClassifier - index can't contain negative values

### ISSUE THREAD

**Issue by bassemfg** [sktime/sktime#5294]
```
Traceback (most recent call last):
  File "/home/bassem/code/my-env/Link to transforms/train_matrix_profile_clf.py", line 116, in <module>
    clf.fit(X_train_transformed[:, feature_, :], y_train)
  File "/home/bassem/anaconda3/envs/my-env/lib/python3.9/site-packages/sktime/classification/base.py", line 202, in fit
    self._fit(X, y)
  File "/home/bassem/anaconda3/envs/my-env/lib/python3.9/site-packages/sktime/classification/feature_based/_matrix_profile_classifier.py", line 126, in _fit
    X_t = self._transformer.fit_transform(X, y)
  File "/home/bassem/anaconda3/envs/my-env/lib/python3.9/site-packages/sktime/transformations/base.py", line 623, in fit_transform
    return self.fit(X, y).transform(X, y)
  File "/home/bassem/anaconda3/envs/my-env/lib/python3.9/site-packages/sktime/transformations/base.py", line 537, in transform
    Xt = self._transform(X=X_inner, y=y_inner)
  File "/home/bassem/anaconda3/envs/my-env/lib/python3.9/site-packages/sktime/transformations/panel/matrix_profile.py", line 242, in _transform
    Xt = pd.DataFrame([_stomp_self(X[i], self.m) for i in range(n_instances)])
  File "/home/bassem/anaconda3/envs/my-env/lib/python3.9/site-packages/sktime/transformations/panel/matrix_profile.py", line 242, in <listcomp>
    Xt = pd.DataFrame([_stomp_self(X[i], self.m) for i in range(n_instances)])
  File "/home/bassem/anaconda3/envs/my-env/lib/python3.9/site-packages/sktime/transformations/panel/matrix_profile.py", line 166, in _stomp_self
    dot_prod = _sliding_dot_products(ts[0:m], ts, m, ts_len)
  File "/home/bassem/anaconda3/envs/my-env/lib/python3.9/site-packages/sktime/transformations/panel/matrix_profile.py", line 33, in _sliding_dot_products
    q_reversed_padded = np.pad(q_reversed, (0, 2 * t_len - q_len))
  File "/home/bassem/anaconda3/envs/my-env/lib/python3.9/site-packages/numpy/lib/arraypad.py", line 748, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
  File "/home/bassem/anaconda3/envs/my-env/lib/python3.9/site-packages/numpy/lib/arraypad.py", line 514, in _as_pairs
    raise ValueError("index can't contain negative values")
ValueError: index can't contain negative values
```
**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by fkiraly** [comment]
Maybe not a bug, as per the `numpy3D` convention, your time series are one time stamp long.

If you want 72000 univariate time series of length 590, the shape should be `(72000, 1, 590)`.

**Comment by bassemfg** [comment]
Thanks for you response. I tried your suggestion, and every other possible combination, but I still keep getting the same error.

**Comment by fkiraly** [comment]
Thanks for reporting, @bassemfg - can you paste your self-contained code that produces the error in the updated case?

**Comment by bassemfg** [comment]
my dataset is too large to share unfortunately but here is how I fixed the issue:
```python

df = normalized_subset

# Read labels
df_lbl = pd.read_csv("labeled.csv", parse_dates=True, index_col=0).sort_index()
y = df_lbl[-n_rows:]["label"].values
y[y == -1] = 0

# Split the data into training and testing subsets
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, shuffle=False)

def reshape_to_univariate(df_2d):
    """
    Transforms a 2D DataFrame to a 3D array for univariate time series analysis.
    The resulting shape is (n_samples, 1, n_features).
    """
    return df_2d.values.reshape(-1, 1, df_2d.shape[1])

X_train_transformed = reshape_to_univariate(X_train)
X_test_transformed = reshape_to_univariate(X_test)

print(f"Minimum length of time series: {min(len(x) for x in X_train_transformed)}")
print(X_train_transformed.shape)

def series_from_row(row):
    return pd.Series(row)

def array_to_nested_dataframe(arr):
    """
    Convert a 3D array to a nested DataFrame without multi-threading.
    """
    nested_df = pd.DataFrame()
    for idx in range(arr.shape[2]):
        nested_df[idx] = [pd.Series(row) for row in arr[:, 0, :]]
    return nested_df

X_train_df = array_to_nested_dataframe(X_train_transformed)
X_test_df = array_to_nested_dataframe(X_test_transformed)
classifiers = []
predictions = []

n_features = X_train.shape[1]
for feature_ in range(n_features):
    print(f"feature {feature_}")
    clf = MatrixProfileClassifier(subsequence_length=20,n_jobs=-1)
    clf.fit(X_train_df[[feature_]], y_train)
    y_pred = clf.predict(X_test_df[feature_])
    clf.save(f"_{feature_}_mp_clf.pkl")
    classifiers.append(clf)
    predictions.append(y_pred)
    print(clf)
    print(clf.score(X_test_df, y_pred))
```

**Comment by fkiraly** [comment]
> my dataset is too large to share unfortunately

I meant, you could generate a similar random dataset with `numpy.random`, to provoke the error?

**Comment by bassemfg** [comment]
sure. here you go
```python
from concurrent.futures import ThreadPoolExecutor
from fastai.callback import *
from sktime.classification.interval_based import (
    CanonicalIntervalForest,
    DrCIF,
    RandomIntervalSpectralEnsemble,
    SupervisedTimeSeriesForest,
    TimeSeriesForestClassifier,
)
from sklearn import metrics
from sktime.datasets import load_unit_test
from sktime.classification.feature_based import MatrixProfileClassifier
import sys
from fastai.vision import *
from fastai.callback.progress import CSVLogger
import joblib
from sktime.datatypes import check_raise
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import numpy as np
import pandas as pd
import gc
import torch
from tsai.models.MINIROCKET_Pytorch import *
from tsai.models.utils import *
from tsai.basics import *
from sklearn.model_selection import train_test_split
from fastai.learner import *
import numpy as np
from sklearn.linear_model import RidgeClassifierCV
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from tsai.models.MINIROCKET import *

from tsai.basics import *
import sktime
import sklearn
my_setup(sktime, sklearn)
from sktime.datasets import load_arrow_head  # univariate dataset
from sktime.datasets import load_basic_motions  # multivariate dataset
from sktime.datasets import (
    load_japanese_vowels,  # multivariate dataset with unequal length
)
from sktime.transformations.panel.rocket import (
    MiniRocket,
    MiniRocketMultivariate,
    MiniRocketMultivariateVariable,)
# Set environment
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
os.chdir(os.path.abspath(os.path.join(os.path.dirname(__file__))))


# Number of rows and columns
n_rows = 10000
n_cols = 500

# Generating the random data
data = np.random.rand(n_rows, n_cols)

# Creating the DataFrame
df = pd.DataFrame(data)
# Generating the random data
data = np.random.choice([0, 1], size=n_rows)

# Creating the DataFrame
y = pd.DataFrame(data, columns=['value'])
# Ensure you have the necessary imports

# Split the data into training and testing subsets
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, shuffle=False)
y_train = y_train.values.ravel()
y_test = y_test.values.ravel()


def transform_to_univariate(df_2d):
    # Assuming df_2d has shape (n_samples, n_features)
    # Reshape to (n_samples, n_features, 1)
    return df_2d.values.reshape(df_2d.shape[0],1, df_2d.shape[1] )


X_train_transformed = transform_to_univariate(X_train)
X_test_transformed = transform_to_univariate(X_test)

min_length = min([len(x) for x in X_train_transformed])
print(f"Minimum length of time series: {min_length}")
print(X_train_transformed.shape)

classifiers = []
predictions = []

n_features = X_train_transformed.shape[1]

for feature_ in range(n_features):
    print(f"feature {feature_}")
    clf = MatrixProfileClassifier(subsequence_length=20,n_jobs=-1)
    clf.fit(X_train_transformed[:,:,feature_], y_train)
    y_pred = clf.predict(X_test_transformed[feature_])
    clf.save(f"_{feature_}_mp_clf.pkl")
    classifiers.append(clf)
    predictions.append(y_pred)
    print(clf)
    print(clf.score(X_test_transformed, y_pred))
```

**Comment by fkiraly** [comment]
Thanks!

Could you kindly remove all custom functions and unneeded imports? I do not have `my_setup`, for instance.
