### ISSUE TITLE
pushes to PR's failing immediately because of Contributors update

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5372]
Traceback

```
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

Examples:

1. https://github.com/yarnabrina/sktime-fork/actions/runs/6435382873/job/17476526494
2. https://github.com/yarnabrina/sktime-fork/actions/runs/6435442447/job/17476720713
3. https://github.com/yarnabrina/sktime-fork/actions/runs/6435457989/job/17476772479

It seems that it is trying to push into my fork automatically, and failing becuase of access. Is there some new workflow or update that is affecting this?

**Comment by fkiraly** [comment]
I think this is from the contributors-update workflow `update_contributors` - this triggers on every branch whenever there is a new contributor in the `allcontributorsrc`, and automatically updates the branch, see issue https://github.com/sktime/sktime/issues/4103

@achieveordie implemented this - it works but has some downsides which we never were able to find a fix for - it tries to push to all branches after it detects that an update is needed, and that will fail for `main` and fork branches. Although this minor annoyance is only temporary, until the contributors upgrade gets merged with any one branch.

imo the upsides of this CI element outweigh the downsides, although someone with GHA experience might see how to fix the downsides.

**Comment by yarnabrina** [comment]
Okay, so it's a known issue? I don't know why, but this never happened to me before. Yesterday I got multiple mails each time I updated a PR.

I've really no familiarity with `all-contributors`, but I see this page suggests some bot and etc. If we use that, will it help anything?

https://allcontributors.org/docs/en/bot/usage

(As you said, not really a priority thing, but just noting that it may be demotivating for first time contributors who may think they are doing something wrong.)

**Comment by fkiraly** [comment]
> https://allcontributors.org/docs/en/bot/usage

I think the bot didn't properly work, it was the first thing we tried.

@achieveordie can maybe say more about this, he spent a lot of time on trying to make it work.

**Comment by fkiraly** [comment]
> but just noting that it may be demotivating for first time contributors who may think they are doing something wrong

But isn't that always mitigated by the fact that a core dev has to approve the CI run anyway?

**Comment by yarnabrina** [comment]
I know that we have to approve CI workflows, but I think only those that run in Github CI. For example, read-the-docs workflow will always run.

I do not know whether the (temporarily) failing pipeline runs within Github or somewhere else, so I'm not certain if first time contributors are getting this failure or not. But if it's in Github workers and don't run automatically for all, then yes, my above comment is invalid.

**Comment by fkiraly** [comment]
But still it's unexpected and annoying - any ideas how to improve the state of affairs?

**Comment by achieveordie** [comment]
The bot still requires manual input from a core developer via a GH comment which essentially removes the automation aspect of it, that is why we chose to use an action to completely automate it.

This issue is known and is only triggered under a specific condition, since this was done a while ago I don't remember the exact reason for this behaviour but its mostly harmless.

In any case, let me dig through again and maybe this time I'd be able to find another way to circumvent this issue.
