### ISSUE TITLE
[BUG] `pycatch` dependency full breakage on windows systems

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5435]
We are experiencing failures from `pycatch` install, likely related to the 0.4.4 release on Oct 16 (today).

This happens on all windows systems, but not mac and unix, at attempted install of `pycatch 0.4.4`. Error log:

```
Collecting pycatch22 (from sktime==0.24.0)
  Downloading pycatch22-0.4.4.tar.gz (49 kB)
     ---------------------------------------- 49.9/49.9 kB ? eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [15 lines of output]
  Traceback (most recent call last):
    File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2prn_dvq\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2prn_dvq\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2prn_dvq\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 11, in <module>
  AttributeError: 'NoneType' object has no attribute 'split'
  [end of output]
```

**Comment by benfulcher** [comment]
Not sure what's happening here. A quick fix would be to specify v0.4.2 for Windows systems.

**Comment by fkiraly** [comment]
> A quick fix would be to specify v0.4.2 for Windows systems.

Yes, that's what PR #5434 does, but of course it's only a temp fix.

**Comment by fkiraly** [comment]
oh, you mean, only for windows? Not sure how to do that with `pyproject.toml`, i.e., OS specific bounds. The PR bounds it overall.

**Comment by benfulcher** [comment]
Ah I see… Temp fix sounds fine, maybe someone more knowledgeable will find the OS-dependent issue.

**Comment by anniegbryant** [comment]
Just to confirm mac functionality -- I'm running macOS (Ventura 13.6) and just created a clean conda environment using python 3.8.10 to replicate the environment as closely as possible, ran `python3 -m pip install pycatch22==0.4.4` and had a clean install. @fkiraly are you using a Conda environment? I wonder if perhaps this is related to a specific version of python within Windows OS?

**Comment by fkiraly** [comment]
This is from the CI, not my local computer, here:

https://github.com/sktime/sktime/blob/main/.github/workflows/test.yml

(config starting line 172)
