### ISSUE TITLE
[BUG] broken MACNNClassifier and MACNNRegressor

### ISSUE THREAD

**Issue by helloplayer1** [sktime/sktime#6465]
**Describe the bug**
When you try to fit either of them, an error is raised.
**To Reproduce**

```python
import pandas as pd
import numpy as np
from sktime.regression.deep_learning import MACNNRegressor
from sktime.classification.deep_learning import MACNNClassifier
from sktime.regression.deep_learning import MCDCNNRegressor


index = pd.MultiIndex.from_tuples([
    (0, 0),
    (0, 1),
    (1, 0),
    (1, 1)
], names=['instance', 'Time'])

# Define the DataFrame
df = pd.DataFrame({
    'LeftControllerVelocity_0': [-0.01, -0.01, 0.06, 0.06]
}, index=index)

regressor = MACNNClassifier()

regressor.fit(df, np.array([1, 0]))

regressor.predict(df)
```

**Expected behavior**
The model is fitted
**Additional context**
The following error is raised:
```
Traceback (most recent call last):
  File "D:\BAAI\bug_report.py", line 22, in <module>
    regressor.fit(df, np.array([1, 0]))
  File "d:\BAAI\.venv\Lib\site-packages\sktime\classification\base.py", line 262, in fit
    self._fit(X, y)
  File "d:\BAAI\.venv\Lib\site-packages\sktime\classification\deep_learning\macnn.py", line 209, in _fit
    self.model_ = self.build_model(self.input_shape, self.n_classes_)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\sktime\classification\deep_learning\macnn.py", line 169, in build_model
    input_layer, output_layer = self._network.build_network(input_shape, **kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\sktime\networks\macnn.py", line 146, in build_network
    x = self._stack(input_layer, self.repeats, self.filter_sizes[0], self.reduction)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\sktime\networks\macnn.py", line 124, in _stack
    x = self._macnn_block(x, kernels, reduce)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\sktime\networks\macnn.py", line 94, in _macnn_block
    x2 = reduce_mean(x1, 1)
         ^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\tensorflow\python\ops\weak_tensor_ops.py", line 88, in wrapper
    return op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "d:\BAAI\.venv\Lib\site-packages\keras\src\backend\common\keras_tensor.py", line 91, in __tf_tensor__
    raise ValueError(
ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:

\`\`\`
x = Input(...)
...
tf_fn(x)  # Invalid.
\`\`\`

What you should do instead is wrap `tf_fn` in a layer:

\`\`\`
class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)
\`\`\`
```

**Versions**
<details>
System:
    python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
executable: d:\BAAI\.venv\Scripts\python.exe
   machine: Windows-11-10.0.22631-SP0

Python dependencies:
          pip: 24.0
       sktime: 0.29.0
      sklearn: 1.4.2
       skbase: 0.7.7
        numpy: 1.26.4
        scipy: 1.13.0
       pandas: 2.2.2
   matplotlib: 3.8.4
       joblib: 1.4.0
        numba: 0.59.1
  statsmodels: 0.14.2
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: 0.6.3
        torch: None
   tensorflow: 2.16.1
tensorflow_probability: None
</details>

**Comment by EmanAbdelhaleem** [comment]
Hi, I think this issue is outdated, right?
cuz I have tried to reproduce using the above code and it works fine with me.

**Comment by fkiraly** [comment]
@helloplayer1, I also cannot reproduce this on the most recent version of `sktime`, 0.40.0 - I would recommend you update your version (0.29.0), the bug is probably fixed since then.

**Comment by helloplayer1** [comment]
thanks for checking 👍
