### ISSUE TITLE
[BUG] CNTCRegressor raises an error on calling .fit()

### ISSUE THREAD

**Issue by helloplayer1** [sktime/sktime#6467]
**Describe the bug**
There is an error raised on calling fit on a `CNTCRegressor`.

**To Reproduce**
```python
import pandas as pd
import numpy as np
from sktime.regression.deep_learning import CNTCRegressor

index = pd.MultiIndex.from_tuples([
    (0, 0),
    (0, 1),
    (1, 0),
    (1, 1)
], names=['instance', 'Time'])

# Define the DataFrame
df = pd.DataFrame({
    'LeftControllerVelocity_0': [-0.01, -0.01, 0.06, 0.06]
}, index=index)

regressor = CNTCRegressor(verbose=True)

regressor.fit(df, np.array([1, 0]))

print(regressor.predict(df))
```

**Expected behavior**
The model is fitted.
**Additional context**
The following error is raised:
```
d:\BAAI\.venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
Traceback (most recent call last):
  File "D:\BAAI\bug_report.py", line 19, in <module>
    regressor.fit(df, np.array([1, 0]))
  File "d:\BAAI\.venv\Lib\site-packages\sktime\regression\base.py", line 245, in fit
    self._fit(X, y)
  File "d:\BAAI\.venv\Lib\site-packages\sktime\regression\deep_learning\cntc.py", line 223, in _fit
    self.model_ = self.build_model(self.input_shape)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\sktime\regression\deep_learning\cntc.py", line 125, in build_model
    input_layer, output_layer = self._network.build_network(input_shape, **kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\sktime\networks\cntc.py", line 135, in build_network
    conc1 = keras.layers.Concatenate(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "d:\BAAI\.venv\Lib\site-packages\keras\src\layers\merging\concatenate.py", line 97, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concatenation axis. Received: input_shape=[(None, 2, 1), (None, 64, 1)]
```

**Versions**
<details>
System:
    python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
executable: d:\BAAI\.venv\Scripts\python.exe
   machine: Windows-11-10.0.22631-SP0

Python dependencies:
          pip: 24.0
       sktime: 0.29.0
      sklearn: 1.4.2
       skbase: 0.7.7
        numpy: 1.26.4
        scipy: 1.13.0
       pandas: 2.2.2
   matplotlib: 3.8.4
       joblib: 1.4.0
        numba: 0.59.1
  statsmodels: 0.14.2
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: 0.6.3
        torch: None
   tensorflow: 2.16.1
tensorflow_probability: None
</details>

**Comment by sanskarmodi8** [comment]
Hey @helloplayer1, I looked into the issue and found out that the input format you're passing is not correct.
The required input shape is 3 dimensional (n_instances(n), n_dimensions(d), series_length(m)).

So, you need to reshape your 2D data like `df = df.values.reshape(n, d, m)` before passing to the model.

Although, there should be input validation in sktime to display clearer message to the user to avoid confusion. Hence, I'm opening a PR regarding the same - https://github.com/sktime/sktime/pull/7269.

**Comment by fkiraly** [comment]
@sanskarmodi8, @helloplayer1, sorry to unterrupt, but the `pandas` `MultiIndex` format should work.

The boilerplate in `fit` should successfully convert the input to a 3D `numpy` array, so I am wondering why this does not seem to happen.

**Comment by sanskarmodi8** [comment]
Hey @fkiraly, I checked out what is causing the problem and find out that the `_internal_convert` function in `BasePanelMixin` Class in responsible for converting the input data from 2d to 3d. But the function only checks for the case where the input if of type `np.ndarray`.

So, should I update the function to handle pandas Dataframe inputs also?

The updated function will look like - 

bash ```
def _internal_convert(self, X, y=None):
    """Convert X and y if necessary as a user convenience.

    Convert X to a 3D numpy array if already a 2D and convert y into an 1D numpy
    array if passed as a Series.

    Parameters
    ----------
    X : an object of a supported Panel mtype, or 2D numpy.ndarray
    y : np.ndarray or pd.Series

    Returns
    -------
    X: an object of a supported Panel mtype, numpy3D if X was a 2D numpy.ndarray
    y: np.ndarray
    """
    if isinstance(X, np.ndarray):
        # Temporary fix to insist on 3D numpy. For univariate problems,
        # most panel estimators simply convert back to 2D. This squeezing should be
        # done here, but touches a lot of files, so will get this to work first.
        if X.ndim == 2:
            X = X.reshape(X.shape[0], 1, X.shape[1])
    elif isinstance(X, pd.core.frame.DataFrame):
        print(f"debug base before convert- {X.shape}")
        X = X.values.reshape(len(X.index.levels[0]), len(X.index.levels[1]), X.shape[1])
        print(f"debug base after convert- {X.shape}")
    if y is None:
        return X
    return X, y
   bash ```

**Comment by fkiraly** [comment]
There are two conversions - pre-conversion via `_internal_convert`, then in side `fit`, the function `_convert_X` is called. This should convert the pandas based container to `numpy3D`. Is this not happening?

**Comment by sanskarmodi8** [comment]
> There are two conversions - pre-conversion via `_internal_convert`, then in side `fit`, the function `_convert_X` is called. This should convert the pandas based container to `numpy3D`. Is this not happening?

The _convert_X function is transforming the data into like -
```
array([[[-0.01, -0.01]],

       [[ 0.06,  0.06]]])
```
But the correct required format is like -
```
array([[[-0.01],
        [-0.01]],

       [[ 0.06],
        [ 0.06]]])
```
When we are doing `X.values.reshape(len(X.index.levels[0]), len(X.index.levels[1]), X.shape[1])` before the fitting, it's converting the input to the correct format that's the reason we are not getting error if we are using that.

**Comment by sanskarmodi8** [comment]
Hey @fkiraly, I noticed that before the line `X = X.transpose(0, 2, 1)` in fit function we get correct format of data after _convert_X processes it which is like -
```
[[[-0.01 -0.01]]

 [[ 0.06  0.06]]]
```

But the line `X = X.transpose(0, 2, 1)` changes it to -
```
[[[-0.01]
  [-0.01]]

 [[ 0.06]
  [ 0.06]]]
```

When I commented out the transpose line the code worked perfectly fine.
I think the _convert_X function is already converting the input to the required format so there's no need for explicit transpose function.

So should I remove the transpose line from the fit function in my Pull Request?

**Comment by fkiraly** [comment]
> So should I remove the transpose line from the fit function in my Pull Request?

That could be a solution, we need to check though whether this is indeed in the right format, namely (instance, variable, time index).

**Comment by sanskarmodi8** [comment]
Hey @fkiraly, I think from the below outputs it's clear that the input is correctly converted into the right format after _convert_X function call (namely, (instance, variable, time index)).
The transpose function is changing it in the incorrect format.

Output with transpose function - 
```
passing df to fit. Current df -:

               LeftControllerVelocity_0
instance Time                          
0        0                        -0.01
         1                        -0.01
1        0                         0.06
         1                         0.06

shape of current df => (4, 1)

required shape - (2,1,2) (index, variable, time-index)


_convert_X function started. X , now, -:

               LeftControllerVelocity_0
instance Time                          
0        0                        -0.01
         1                        -0.01
1        0                         0.06
         1                         0.06

Shape of X, now, => (4, 1)

_convert_X function completed. X , now, -:

[[[-0.01 -0.01]]

 [[ 0.06  0.06]]]

Shape of X, now, => (2, 1, 2)


Transpose completed. X, now, -:

[[[-0.01]
  [-0.01]]

 [[ 0.06]
  [ 0.06]]]

shape of X, now, => (2, 2, 1)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-26-2155ac33f9ae>](https://localhost:8080/#) in <cell line: 28>()
     26 print('required shape - (2,1,2) (index, variable, time-index)\n')
     27 
---> 28 regressor.fit(df, np.array([1, 0]))
     29 
     30 print(regressor.predict(df))

5 frames
[/usr/local/lib/python3.10/dist-packages/keras/src/layers/merging/concatenate.py](https://localhost:8080/#) in build(self, input_shape)
     95                 )
     96                 if len(unique_dims) > 1:
---> 97                     raise ValueError(err_msg)
     98         self.built = True
     99 

ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concatenation axis. Received: input_shape=[(None, 2, 1), (None, 64, 1)]
```

Output after commenting the Transpose function in fit method -

```
passing df to fit. Current df -:

               LeftControllerVelocity_0
instance Time                          
0        0                        -0.01
         1                        -0.01
1        0                         0.06
         1                         0.06

shape of current df => (4, 1)

required shape - (2,1,2) (index, variable, time-index)


_convert_X function started. X , now, -:

               LeftControllerVelocity_0
instance Time                          
0        0                        -0.01
         1                        -0.01
1        0                         0.06
         1                         0.06

Shape of X, now, => (4, 1)

_convert_X function completed. X , now, -:

[[[-0.01 -0.01]]

 [[ 0.06  0.06]]]

Shape of X, now, => (2, 1, 2)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
Model: "functional"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_14            │ (None, 1, 2)           │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ input_layer_15            │ (None, 1, 2)           │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv1d_7 (Conv1D)         │ (None, 1, 16)          │             48 │ input_layer_14[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ simple_rnn_7 (SimpleRNN)  │ (None, 128)            │         16,768 │ input_layer_15[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ batch_normalization_14    │ (None, 1, 16)          │             64 │ conv1d_7[0][0]         │
│ (BatchNormalization)      │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ batch_normalization_15    │ (None, 128)            │            512 │ simple_rnn_7[0][0]     │
│ (BatchNormalization)      │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_14 (Dropout)      │ (None, 1, 16)          │              0 │ batch_normalization_1… │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_15 (Dropout)      │ (None, 128)            │              0 │ batch_normalization_1… │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_7 (Dense)           │ (None, 1, 2)           │             34 │ dropout_14[0][0]       │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ reshape_7 (Reshape)       │ (None, 64, 2)          │              0 │ dropout_15[0][0]       │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ contextual_convolutional… │ (None, 65, 2)          │              0 │ dense_7[0][0],         │
│ (Concatenate)             │                        │                │ reshape_7[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ standard_cnn_layer        │ (None, 65, 8)          │             24 │ contextual_convolutio… │
│ (Conv1D)                  │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ input_layer_16            │ (None, 1, 2)           │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_8 (Dense)           │ (None, 65, 2)          │             18 │ standard_cnn_layer[0]… │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ lstm (LSTM)               │ (None, 16)             │          1,216 │ input_layer_16[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ batch_normalization_16    │ (None, 65, 2)          │              8 │ dense_8[0][0]          │
│ (BatchNormalization)      │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ reshape_8 (Reshape)       │ (None, 8, 2)           │              0 │ lstm[0][0]             │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_16 (Dropout)      │ (None, 65, 2)          │              0 │ batch_normalization_1… │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_17 (Dropout)      │ (None, 8, 2)           │              0 │ reshape_8[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ contextual_convolutional… │ (None, 73, 2)          │              0 │ dropout_16[0][0],      │
│ (Concatenate)             │                        │                │ dropout_17[0][0]       │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ max_pooling1d             │ (None, 73, 2)          │              0 │ contextual_convolutio… │
│ (MaxPooling1D)            │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_18 (Dropout)      │ (None, 73, 2)          │              0 │ max_pooling1d[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ Attention                 │ (None, 73, 2)          │              5 │ dropout_18[0][0]       │
│ (SeqSelfAttention)        │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_19 (Dropout)      │ (None, 73, 2)          │              0 │ Attention[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_9 (Dense)           │ (None, 73, 64)         │            192 │ dropout_19[0][0]       │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_20 (Dropout)      │ (None, 73, 64)         │              0 │ dense_9[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_10 (Dense)          │ (None, 73, 64)         │          4,160 │ dropout_20[0][0]       │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dropout_21 (Dropout)      │ (None, 73, 64)         │              0 │ dense_10[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ flatten (Flatten)         │ (None, 4672)           │              0 │ dropout_21[0][0]       │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_11 (Dense)          │ (None, 1)              │          4,673 │ flatten[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘
 Total params: 27,722 (108.29 KB)
 Trainable params: 27,430 (107.15 KB)
 Non-trainable params: 292 (1.14 KB)
Epoch 1/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 7s 7s/step - accuracy: 0.5000 - loss: 0.7364
Epoch 2/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 0.5000 - loss: 0.5378
Epoch 3/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.4778
Epoch 4/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.3958
Epoch 5/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.3199
Epoch 6/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.2586
Epoch 7/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.1974
Epoch 8/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 1.0000 - loss: 0.1022
Epoch 9/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.0204
Epoch 10/2000
```

So should i update my Pull Request to discard any previous change I suggested and just remove the line `X = X.transpose(0, 2, 1)` from the fit method of CNTCRegressor Class?

**Comment by fkiraly** [comment]
Yes, I think that is the solution! Let's do that, and you can also get the `bug` badge since you helped diagnose the bug!

**Comment by sanskarmodi8** [comment]
> Yes, I think that is the solution! Let's do that, and you can also get the `bug` badge since you helped diagnose the bug!

That's good. I have updated my PR accordingly.
