### ISSUE TITLE
[BUG] vmdpy - Memory Error

### ISSUE THREAD

**Issue by saitejach1998** [sktime/sktime#6608]
```python
alpha = 10000
tau = 0
K = 3
DC = 1
init = 1
tol = K*pow(10,-6)
f = image_lab[:,:,2] #f's shape is (900,1600)
u = VMD(f, alpha, tau, K, DC, init, tol)
```

Throws
```
Traceback (most recent call last):
  File "vmd_test.py", line 17, in <module>
    u = VMD(f, alpha, tau, K, DC, init, tol)
  File "C:\Python36\lib\site-packages\vmdpy\vmdpy.py", line 91, in VMD
    u_hat_plus = np.zeros([Niter, len(freqs), K],dtype=complex)
MemoryError

```
any possible work arounds?

**Comment by jbbqqf** [comment]
Hi! Triaging older issues this week — I think the premise here doesn't match what `VMD` is for.

The snippet calls `VMD(f, ...)` with `f = image_lab[:, :, 2]`, i.e. a `(900, 1600)` 2-D image channel. `VMD` (Variational Mode Decomposition, Dragomiretskiy & Zosso 2014) is defined for **1-D real-valued signals**, and `sktime.libs.vmdpy` implements it for 1-D arrays:

- [`sktime/libs/vmdpy/vmdpy.py`](https://github.com/sktime/sktime/blob/main/sktime/libs/vmdpy/vmdpy.py) — `VMD(f, alpha, tau, K, DC, init, tol)` expects `f` as a 1-D signal.

The `MemoryError` at `np.zeros([Niter, len(freqs), K], dtype=complex)` is the algorithm faithfully trying to allocate `~Niter * 1_440_000 * K` complex cells for a flattened 1.44M-sample "signal" — that's the input shape, not a library bug. The fix is to run `VMD` per 1-D series (e.g. one image row, or a column of a time-series matrix), not on a 2-D image.

If I'm misreading the use-case, point me at the upstream paper/example that uses 2-D VMD and I'll dig further. Otherwise this looks like a candidate to close.

(Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against the current `main` branch at commit `bd8fe08`.)
