### ISSUE TITLE
[MNT] `numpy 2` compatibility

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6625]
`numpy 2` has been released, and we need to check compatibility of estimators before we bump the bound with the next release.

`test-nosoftdeps-full` should take care of the minimal dependency set, although this covers only a single python version and OS.

We should perhaps run a diagnostic with all combinations on minimal dependeny sets.

**Comment by fkiraly** [comment]
From https://github.com/sktime/sktime/actions/runs/9539651850/job/26290292568, it appears that `pandas 1.5.3` and `numpy 2.0.0` are mutually incompatible.

<details>
```
rm -rf testdir
mkdir -p testdir
cp .coveragerc testdir
cp setup.cfg testdir
python -m pytest --ignore sktime/datasets
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/_pytest/main.py", line 281, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1130, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pluggy/_hooks.py", line 535, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self._hookimpls.copy(), kwargs, False)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/runner/work/sktime/sktime/conftest.py", line 51, in pytest_configure
INTERNALERROR>     from sktime.tests import test_all_estimators
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
INTERNALERROR>     exec(co, module.__dict__)
INTERNALERROR>   File "/home/runner/work/sktime/sktime/sktime/tests/test_all_estimators.py", line 18, in <module>
INTERNALERROR>     import pandas as pd
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
INTERNALERROR>     from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pandas/compat/__init__.py", line 18, in <module>
INTERNALERROR>     from pandas.compat.numpy import (
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
INTERNALERROR>     from pandas.util.version import Version
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pandas/util/__init__.py", line 2, in <module>
INTERNALERROR>     from pandas.util._decorators import (  # noqa:F401
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
INTERNALERROR>     from pandas._libs.properties import cache_readonly
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
INTERNALERROR>     from pandas._libs.interval import Interval
INTERNALERROR>   File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
INTERNALERROR> ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
make: *** [Makefile:45: test_without_datasets] Error 3
```
<\details>

**Comment by patrick-rice-lang** [comment]
I think this issue can be closed as complete.

**Comment by fkiraly** [comment]
yes. Probably accidentally not linked.
