### ISSUE TITLE
[BUG] Unexpected behaviors with DynamicFactor, PyKANForecaster, and SquaringResiduals

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [sktime/sktime#6652]
**Describe the bug**

Before https://github.com/sktime/sktime/pull/6593, `DynamicFactor` and `PyKANForecaster` are not raising `NotImplementedError` with insample input. They won't pass `check_estimator` but no error in the CI. `SquaringResiduals` is taged `"capability:insample": False` but it passes insample tests.

After #6593 is merged, `NotImplementedError` will be raised in `BaseForecaster`, this issue is for tracking the unexpected behaviors.

**To Reproduce**

<details>
<summary>`DynamicFactor`</summary>

```py
from sktime.utils.estimator_checks import check_estimator
from sktime.forecasting.dynamic_factor import DynamicFactor

check_estimator(
    DynamicFactor,
    tests_to_run=[
        "test_predict_time_index_in_sample_full",
    ],
    raise_exceptions=True,
)
```
```sh
Traceback (most recent call last):
  File "/home/xinyu/Documents/sktime/sktime-dev/py_scripts/test.py", line 84, in <module>
    check_estimator(
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/sktime/utils/estimator_checks.py", line 116, in check_estimator
    test_cls_results = test_cls().run_tests(
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/sktime/tests/test_all_estimators.py", line 608, in run_tests
    test_fun(**deepcopy(args))
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/sktime/forecasting/tests/test_all_forecasters.py", line 322, in test_predict_time_index_in_sample_full
    y_pred_int = estimator_instance.predict_interval()
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/sktime/forecasting/base/_base.py", line 715, in predict_interval
    pred_int = self._predict_interval(fh=fh, X=X_inner, coverage=coverage)
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/sktime/forecasting/dynamic_factor.py", line 283, in _predict_interval
    y_pred = model.get_forecast(steps=steps, exog=X).conf_int(alpha=alpha)
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 3417, in get_forecast
    return self.get_prediction(start=self.nobs, end=end,
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 3340, in get_prediction
    self.model._get_prediction_index(start, end, index))
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/statsmodels/tsa/base/tsa_model.py", line 836, in _get_prediction_index
    return get_prediction_index(
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/statsmodels/tsa/base/tsa_model.py", line 389, in get_prediction_index
    raise ValueError("Prediction must have `end` after `start`.")
ValueError: Prediction must have `end` after `start`.
```

</details>

<details>
<summary>PyKANForecaster</summary>

```py
from sktime.utils.estimator_checks import check_estimator
from sktime.forecasting.pykan_forecaster import PyKANForecaster

check_estimator(
    PyKANForecaster,
    tests_to_run=[
        "test_predict_time_index_in_sample_full",
    ],
    raise_exceptions=True,
)
```
```sh
Traceback (most recent call last):
  File "/home/xinyu/Documents/sktime/sktime-dev/py_scripts/test.py", line 84, in <module>
    check_estimator(
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/sktime/utils/estimator_checks.py", line 116, in check_estimator
    test_cls_results = test_cls().run_tests(
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/sktime/tests/test_all_estimators.py", line 608, in run_tests
    test_fun(**deepcopy(args))
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/sktime/forecasting/tests/test_all_forecasters.py", line 317, in test_predict_time_index_in_sample_full
    estimator_instance.fit(y_train, fh=fh)
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/sktime/forecasting/base/_base.py", line 391, in fit
    self._fit(y=y_inner, X=X_inner, fh=fh)
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/sktime/forecasting/pykan_forecaster.py", line 181, in _fit
    results = model.train(ds_new, device=self.device, **self._fit_params)
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/kan/KAN.py", line 898, in train
    self.update_grid_from_samples(dataset['train_input'][train_id].to(device))
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/kan/KAN.py", line 243, in update_grid_from_samples
    self.forward(x)
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/kan/KAN.py", line 314, in forward
    x_symbolic, postacts_symbolic = self.symbolic_fun[l](x)
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xinyu/Documents/sktime/env/lib/python3.10/site-packages/kan/Symbolic_KANLayer.py", line 111, in forward
    postacts.append(torch.stack(postacts_))
RuntimeError: stack expects a non-empty TensorList
```

</details>

**Expected behavior**

Raising `NotImplementedError` for insample input.

**Additional context**

There is another version of `SquaringResiduals` that support insample predictions, see gist: [potential bug with fh for in-sample prediction with forecasters that require fh in fit](https://gist.github.com/kcc-lion/9d77bf0820db0ccac114e8933295200e)

**Versions**
<details>

```sh
System:
    python: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]
executable: /home/xinyu/Documents/sktime/env/bin/python
   machine: Linux-6.5.0-41-generic-x86_64-with-glibc2.35

Python dependencies:
          pip: 23.3.1
       sktime: 0.30.1
      sklearn: 1.4.1.post1
       skbase: 0.7.8
        numpy: 1.26.4
        scipy: 1.12.0
       pandas: 2.1.4
   matplotlib: 3.8.3
       joblib: 1.3.2
        numba: 0.59.1
  statsmodels: 0.14.1
     pmdarima: 2.0.4
statsforecast: 1.7.3
      tsfresh: 0.20.2
      tslearn: 0.6.3
        torch: 2.2.1+cu121
   tensorflow: 2.16.1
tensorflow_probability: None
```

**Comment by fkiraly** [comment]
This is a bit troubling.

We should find out whether these are tested at all.

I would suggest to start with a very simple PR, where we intentionally introduce an exception (using `raise ValueError` or similar), in a place that would be tested only in the main CI, e.g., in `_predict`.

The PR should be marked with the label "do nog merge"

**Comment by yarnabrina** [comment]
Related https://github.com/sktime/sktime/issues/5445
