### ISSUE TITLE
[BUG] Unable to save/load LSTMFCNRegressor with "attention=True"

### ISSUE THREAD

**Issue by oda356** [sktime/sktime#6685]
**Describe the bug**
Saving trained `LSTMFCNRegressor` when enabling `attention=True` will raise errors.

Errors look like:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<...>\lib\site-packages\sktime\regression\deep_learning\base.py", line 255, in save
    self.model_.save(keras_path)
  File "<...>\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "<...>\lib\site-packages\sktime\networks\lstmfcn_layers.py", line 864, in get_config
    base_config = super().get_config()
NotImplementedError:
Layer AttentionLSTMCell has arguments ['units', 'activation', 'recurrent_activation', 'attention_activation', 'use_bias', 'kernel_initializer', 'recurrent_initializer', 'attention_initializer', 'bias_initializer', 'unit_forget_bias', 'kernel_regularizer', 'recurrent_regularizer', 'bias_regularizer', 'activity_regularizer', 'attention_regularizer', 'kernel_constraint', 'recurrent_constraint', 'bias_constraint', 'attention_constraint', 'dropout', 'recurrent_dropout', 'return_attention', 'implementation']
in `__init__` and therefore must override `get_config()`.

Example:

class CustomLayer(keras.layers.Layer):
    def __init__(self, arg1, arg2):
        super().__init__()
        self.arg1 = arg1
        self.arg2 = arg2

    def get_config(self):
        config = super().get_config()
        config.update({
            "arg1": self.arg1,
            "arg2": self.arg2,
        })
        return config
```

**To Reproduce**

When save in default behavior without `legacy_save=True` on `BaseDeepRegressor.save()`, it failes like below:
```python
from sktime.regression.deep_learning import LSTMFCNRegressor
from sktime.datasets import load_italy_power_demand
from sktime.base import load
from datetime import datetime

X_train, y_train = load_italy_power_demand(split="train", return_type="numpy3D")
X_new, _ = load_italy_power_demand(split="test", return_type="numpy3D")
estimator=LSTMFCNRegressor(verbose=0,n_epochs=5,attention = True)
estimator.fit(X_train,y_train)
file_name = datetime.now().strftime("%Y%m%d%H%M%S")
estimator.save(file_name)
new_estimator=load(file_name)

new_classifier.predict(X_new)
```

**Expected behavior**
`estimator.save(file_name)` executes successfully.

**Additional context**
Using `legacy_save` can save successfully, but unable to load successfully.
```
estimator.save(file_name, legacy_save=True)
new_estimator=load(file_name)
```

Reports error like below:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<...>\lib\site-packages\sktime\base\_serialize.py", line 126, in load
    return cls.load_from_path(path)
  File "<...>\lib\site-packages\sktime\regression\deep_learning\base.py", line 345, in load_from_path
    cls.model_ = keras.models.load_model(keras_location_legacy)
  File "<...>\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "<...>\lib\site-packages\keras\saving\saved_model\load.py", line 1137, in revive_custom_object
    raise ValueError(
ValueError: Unable to restore custom object of type _tf_keras_rnn_layer. Please make sure that any custom layers are included in the `custom_objects` arg when calling `load_model()` and make sure that all layers implement `get_config` and `from_config`.
```

**Versions**
<details>

<...>\lib\site-packages\_distutils_hack\__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

System:
    python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
executable: <...>\Scripts\python.exe
   machine: Windows-10-10.0.22631-SP0

Python dependencies:
          pip: 24.1
       sktime: 0.29.0
      sklearn: 1.4.2
       skbase: 0.7.8
        numpy: 1.26.4
        scipy: 1.13.1
       pandas: 1.5.3
   matplotlib: 3.9.0
       joblib: 1.4.2
        numba: 0.59.1
  statsmodels: 0.14.2
     pmdarima: 2.0.4
statsforecast: 1.7.5
      tsfresh: 0.20.2
      tslearn: 0.6.3
        torch: None
   tensorflow: 2.10.1
tensorflow_probability: None

</details>

**Comment by fkiraly** [comment]
FYI @benHeid, as related to `legacy_save`.

The issue seems to be non-pickleable custom layers

**Comment by oda356** [comment]
Hi, @fkiraly, @benHeid . I tried some workarounds and seems not working. Would you please share some ideas about what caused this issue？I don't know if I extend the class and overwrites some methods can make it work, do you have any suggestion? Thanks in advance!

**Comment by marcosfelt** [comment]
Just tried reproducing this and am not having any issues (see this Google [colab](https://colab.research.google.com/drive/1cVWGAsqC2yVLgGiZmodCBsd71er9LfnU?usp=sharing)).

However, I ran into another issue when `attention=True`


```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-3-cd6ec7e798a0>](https://localhost:8080/#) in <cell line: 9>()
      7 X_new, _ = load_italy_power_demand(split="test", return_type="numpy3D")
      8 estimator=LSTMFCNRegressor(verbose=0,n_epochs=5,attention = True)
----> 9 estimator.fit(X_train,y_train)
     10 file_name = datetime.now().strftime("%Y%m%d%H%M%S")
     11 estimator.save(file_name)

9 frames
[/usr/local/lib/python3.10/dist-packages/sktime/regression/base.py](https://localhost:8080/#) in fit(self, X, y)
    254                 )
    255 
--> 256         self._fit(X, y)
    257         self.fit_time_ = int(round(time.time() * 1000)) - start
    258 

[/usr/local/lib/python3.10/dist-packages/sktime/regression/deep_learning/lstmfcn.py](https://localhost:8080/#) in _fit(self, X, y)
    176         self.input_shape = X.shape[1:]
    177 
--> 178         self.model_ = self.build_model(self.input_shape)
    179 
    180         if self.verbose:

[/usr/local/lib/python3.10/dist-packages/sktime/regression/deep_learning/lstmfcn.py](https://localhost:8080/#) in build_model(self, input_shape, **kwargs)
    134         tf.random.set_seed(self.random_state)
    135 
--> 136         input_layers, output_layer = self._network.build_network(input_shape, **kwargs)
    137 
    138         output_layer = keras.layers.Dense(units=1)(output_layer)

[/usr/local/lib/python3.10/dist-packages/sktime/networks/lstmfcn.py](https://localhost:8080/#) in build_network(self, input_shape, **kwargs)
     86         if self.attention:
     87             AttentionLSTM = make_attention_lstm()
---> 88             x = AttentionLSTM(self.lstm_size)(x)
     89         else:
     90             x = keras.layers.LSTM(self.lstm_size)(x)

[/usr/local/lib/python3.10/dist-packages/sktime/networks/lstmfcn_layers.py](https://localhost:8080/#) in __init__(self, units, activation, recurrent_activation, attention_activation, use_bias, kernel_initializer, recurrent_initializer, attention_initializer, bias_initializer, unit_forget_bias, kernel_regularizer, recurrent_regularizer, bias_regularizer, activity_regularizer, attention_regularizer, kernel_constraint, recurrent_constraint, bias_constraint, attention_constraint, dropout, recurrent_dropout, implementation, return_sequences, return_state, return_attention, go_backwards, stateful, unroll, **kwargs)
    682                 implementation=implementation,
    683             )
--> 684             super().__init__(
    685                 cell,
    686                 return_sequences=return_sequences,

[/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py](https://localhost:8080/#) in __init__(self, cell, return_sequences, return_state, go_backwards, stateful, unroll, zero_output_for_mask, **kwargs)
    202                 f"Received: cell={cell}"
    203             )
--> 204         super().__init__(**kwargs)
    205 
    206         # If True, the output for masked timestep will be zeros, whereas in the

[/usr/local/lib/python3.10/dist-packages/keras/src/layers/layer.py](https://localhost:8080/#) in __init__(self, activity_regularizer, trainable, dtype, autocast, name, **kwargs)
    267         self._lock = False
    268         Operation.__init__(self, dtype=dtype, name=name)
--> 269         self.activity_regularizer = regularizers.get(activity_regularizer)
    270         input_dim_arg = kwargs.pop("input_dim", None)
    271         if input_dim_arg is not None:

[/usr/local/lib/python3.10/dist-packages/keras/src/layers/layer.py](https://localhost:8080/#) in __setattr__(self, name, value)
   1443                 self._initialize_tracker()
   1444             value = self._tracker.track(value)
-> 1445         return super().__setattr__(name, value)
   1446 
   1447     def __delattr__(self, name):

[/usr/local/lib/python3.10/dist-packages/keras/src/backend/tensorflow/trackable.py](https://localhost:8080/#) in __setattr__(self, name, value)
     26                 trackable=self, value=value, name=name
     27             )
---> 28         super().__setattr__(name, value)
     29 
     30 

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/trackable/autotrackable.py](https://localhost:8080/#) in __setattr__(self, name, value)
     68       value = data_structures.sticky_attribute_assignment(
     69           trackable=self, value=value, name=name)
---> 70     super(AutoTrackable, self).__setattr__(name, value)
     71 
     72   def __delattr__(self, name):

AttributeError: can't set attribute 'activity_regularizer'
```
