### ISSUE TITLE
[BUG] All models failed to fit

### ISSUE THREAD

**Issue by galenseilis** [sktime/sktime#6703]
**Describe the bug**

I'm not sure if this is a bug or if I am just using the package incorrectly. The error was too long, and I did not log it, but I think the bottom section should give the idea of what I am seeing:

```bash
...
/home/galen/projects/try-sktime/.venv/lib/python3.12/site-packages/sktime/forecasting/model_selection/_tune.py:246: FutureWarning: The behavior of Series.argmax/argmin with skipna=False and NAs, or with all-NAs is deprecated. In a future version this will raise ValueError.
  self.best_index_ = results.loc[:, f"rank_{scoring_name}"].argmin()
Traceback (most recent call last):
  File "/home/galen/projects/try-sktime/src/try_sktime/example1.py", line 65, in <module>
    gscv.fit(y_train)
  File "/home/galen/projects/try-sktime/.venv/lib/python3.12/site-packages/sktime/forecasting/base/_base.py", line 391, in fit
    self._fit(y=y_inner, X=X_inner, fh=fh)
  File "/home/galen/projects/try-sktime/.venv/lib/python3.12/site-packages/sktime/forecasting/model_selection/_tune.py", line 249, in _fit
    raise NotFittedError(
sktime.exceptions.NotFittedError: All fits of forecaster failed,
                set error_score='raise' to see the exceptions.
                Failed forecaster: TransformedTargetForecaster(steps=[('deseasonalize_7',
                                    Deseasonalizer(model='multiplicative',
                                                   sp=7)),
                                   ('deseasonalize_365',
                                    Deseasonalizer(model='multiplicative',
                                                   sp=365)),
                                   ('polynomial_detrend',
                                    Detrender(forecaster=PolynomialTrendForecaster())),
                                   ('naive', NaiveForecaster()),
                                   ('non-negative',
                                    FunctionTransformer(func=<function <lambda> at 0x7f0a677e62a0>))])
```

**To Reproduce**

```python
from holidays import country_holidays, financial_holidays
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.forecasting.model_selection import ForecastingGridSearchCV
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.trend import PolynomialTrendForecaster
from sktime.performance_metrics.forecasting import MeanAbsoluteError as MAE
from sktime.split import SlidingWindowSplitter, temporal_train_test_split
from sktime.transformations.series.detrend import Deseasonalizer, Detrender
from sktime.transformations.series.func_transform import FunctionTransformer
from sktime.transformations.series.holiday import HolidayFeatures
from sktime.utils._testing.hierarchical import _make_hierarchical
from sktime.utils.plotting import plot_series

# Data
y = _make_hierarchical(min_timepoints=3600, max_timepoints=3600, all_positive=True)

y_train, y_test = temporal_train_test_split(y, test_size=366)

# Pipeline

forecaster = TransformedTargetForecaster(
    [
        ("deseasonalize_7", Deseasonalizer(model="multiplicative", sp=7)),
        ("deseasonalize_365", Deseasonalizer(model="multiplicative", sp=365)),
        (
            "polynomial_detrend",
            Detrender(forecaster=PolynomialTrendForecaster(degree=1)),
        ),
        ("naive", NaiveForecaster()),
        ("non-negative", FunctionTransformer(lambda y: (y > 0) * y)),
    ]
)

forecaster.fit(y_train)
y_pred = forecaster.predict(fh=range(365 * 10))

cv = SlidingWindowSplitter(
    initial_window=366, window_length=365, start_with_window=True, step_length=1000
)

param_grid = {
    "deseasonalize_7__model": ["multiplicative", "additive"],
    "deseasonalize_365__model": ["multiplicative", "additive"],
    "polynomial_detrend__forecaster__degree": [1, 2],
    "naive__strategy": ["drift", "mean", "last"],
}


print(forecaster.get_params().keys(), "\n")


gscv = ForecastingGridSearchCV(
    forecaster=forecaster, param_grid=param_grid, cv=cv, scoring=MAE
)

gscv.fit(y_train)

# print(gscv.predict(y_test))
```

**Expected behavior**

I expected the model to successfully fit.

**Additional context**

**Versions**
<details>

```python
>>> from sktime import show_versions; show_versions()

System:
    python: 3.12.3 (main, Apr 15 2024, 18:25:56) [Clang 17.0.6 ]
executable: /home/galen/projects/try-sktime/.venv/bin/python3
   machine: Linux-5.15.0-113-generic-x86_64-with-glibc2.35

Python dependencies:
          pip: None
       sktime: 0.30.1
      sklearn: 1.5.0
       skbase: 0.8.1
        numpy: 1.26.4
        scipy: 1.14.0
       pandas: 2.2.2
   matplotlib: 3.9.0
       joblib: 1.4.2
        numba: None
  statsmodels: 0.14.2
     pmdarima: 2.0.4
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None
```

```bash
$ rye --version
rye 0.35.0
commit: 0.35.0 (a1dbc56d4 2024-06-24)
platform: linux (x86_64)
self-python: cpython@3.12.3
symlink support: true
uv enabled: true
```

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

</details>

**Comment by benHeid** [comment]
For debugging it is easier to pass `error_score="raise"` to the init of the grid search, after doing this the error message is: 

`ValueError: x must have 2 complete cycles requires 730 observations. x only has 366 observation(s)`which seems to be raised by `deseasonalize_365`, since it needs at least 730 observations to perform a deseasonalize with a seasonality of 365. However, I agree that this is error message is not as informative as it could be. (@fkiraly perhaps we should try if we can include in the error message which step of a pipeline is failing) 

Furthermore, you need to pass the scoring as an object and not as a class. I.e., `scoring=MAE()`. Please check if this is working for you and if yes close this issue if not please provide additional details.

**Comment by fkiraly** [comment]
> Furthermore, you need to pass the scoring as an object and not as a class. I.e., `scoring=MAE()`. Please check if this is working for you and if yes close this issue if not please provide additional details.

We could actually add a small piece of syntactic sugar here: if a class is passed, it is just constructed with default params.
