### ISSUE TITLE
[BUG] `ForecastX` is failing to be updated with `forecaster_X_exogeneous="complement"`

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#6724]
## Reproducible Code

```python
from sktime.datasets import load_longley

y, X = load_longley()

cols_to_forecast = ["GNPDEFL", "GNP"]
fh = [1, 2, 3, 4]

from sktime.split import temporal_train_test_split

y_train, y_test, X_train, X_test = temporal_train_test_split(y, X, test_size=max(fh))

from sktime.forecasting.arima import ARIMA

forecaster = ARIMA()

from sktime.forecasting.compose import ForecastX

pipeline = ForecastX(
    forecaster.clone(),
    forecaster_X=forecaster.clone(),
    columns=cols_to_forecast,
    forecaster_X_exogeneous="complement",
)

pipeline.fit(y_train, X=X_train, fh=fh)

pipeline.predict(X=X_test.drop(columns=cols_to_forecast))  # worked since #6433

pipeline.update(y_test, X=X_test, update_params=True)  # fails
```

## Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/env/lib/python3.10/site-packages/sktime/forecasting/base/_base.py", line 953, in update
    self._update(y=y_inner, X=X_inner, update_params=update_params)
  File "/path/to/env/lib/python3.10/site-packages/sktime/forecasting/compose/_pipeline.py", line 1632, in _update
    self.forecaster_X_.update(y=self._get_Xcols(X), update_params=update_params)
  File "/path/to/env/lib/python3.10/site-packages/sktime/forecasting/base/_base.py", line 955, in update
    self._vectorize("update", y=y_inner, X=X_inner, update_params=update_params)
  File "/path/to/env/lib/python3.10/site-packages/sktime/forecasting/base/_base.py", line 1941, in _vectorize
    self.forecasters_ = y.vectorize_est(
  File "/path/to/env/lib/python3.10/site-packages/sktime/datatypes/_vectorize.py", line 630, in vectorize_est
    ret = parallelize(
  File "/path/to/env/lib/python3.10/site-packages/sktime/utils/parallel.py", line 72, in parallelize
    ret = para_fun(
  File "/path/to/env/lib/python3.10/site-packages/sktime/utils/parallel.py", line 92, in _parallelize_none
    ret = [fun(x, meta=meta) for x in iter]
  File "/path/to/env/lib/python3.10/site-packages/sktime/utils/parallel.py", line 92, in <listcomp>
    ret = [fun(x, meta=meta) for x in iter]
  File "/path/to/env/lib/python3.10/site-packages/sktime/datatypes/_vectorize.py", line 679, in _vectorize_est_single
    est_i_result = est_i_method(**args_i)
  File "/path/to/env/lib/python3.10/site-packages/sktime/forecasting/base/_base.py", line 953, in update
    self._update(y=y_inner, X=X_inner, update_params=update_params)
  File "/path/to/env/lib/python3.10/site-packages/sktime/forecasting/base/adapters/_pmdarima.py", line 75, in _update
    self._forecaster.update(y, X=X)
  File "/path/to/env/lib/python3.10/site-packages/pmdarima/arima/arima.py", line 931, in update
    X = self._check_exog(X)  # type: np.ndarray
  File "/path/to/env/lib/python3.10/site-packages/pmdarima/arima/arima.py", line 629, in _check_exog
    raise ValueError('When an ARIMA is fit with an X '
ValueError: When an ARIMA is fit with an X array, it must also be provided one for predicting or updating observations.
```

## Version

```
System:
    python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:53:34) [Clang 16.0.6 ]
executable: /pth/to/env/bin/python
   machine: macOS-14.5-x86_64-i386-64bit

Python dependencies:
          pip: 24.1.1
       sktime: 0.30.2
      sklearn: 1.4.2
       skbase: 0.7.8
        numpy: 1.26.4
        scipy: 1.13.1
       pandas: 2.2.2
   matplotlib: 3.9.0
       joblib: 1.4.2
        numba: 0.59.1
  statsmodels: 0.14.2
     pmdarima: 2.0.4
statsforecast: 1.7.5
      tsfresh: None
      tslearn: 0.6.3
        torch: None
   tensorflow: None
tensorflow_probability: None
```

## Note

If `forecaster_X_exogeneous="complement"` is removed from the reproducible code above, it starts working.

FYI @benHeid @fnhirwa

**Comment by fnhirwa** [comment]
@yarnabrina this is an issue with how the `update` method is being called.
Going to push a fix.
