### ISSUE TITLE
[BUG] `catboost` no longer works with `make_reduction`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#6956]
Reported by @yarnabrina on discord:
```python
from catboost import CatBoostRegressor
from sktime.forecasting.compose import make_reduction

make_reduction(CatBoostRegressor(), strategy="recursive", pooling="global")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aniray1/conda-environments/forecast/lib/python3.10/site-packages/sktime/forecasting/compose/_reduce.py", line 1592, in make_reduction
    scitype = _infer_scitype(estimator)
  File "/Users/aniray1/conda-environments/forecast/lib/python3.10/site-packages/sktime/forecasting/compose/_reduce.py", line 1634, in _infer_scitype
    inferred_skt_scitype = scitype(estimator)
  File "/Users/aniray1/conda-environments/forecast/lib/python3.10/site-packages/sktime/registry/_scitype.py", line 66, in scitype
    raise TypeError("Error, no scitype could be determined for obj")
TypeError: Error, no scitype could be determined for obj
>>> 
```

The reason is a combination of two:

* we replaced the scitype inference in `make_reduction` to allow for a broader set of types
* but a "raise" flag was set, instead of defaulting to `tabular-regressor`

In a case where an estimator is passed that is not entirely `sklearn` compatible (e.g., scitype cannot be inferred due to lack of ineritance from `sklearn` `BaseEstimator`) but implements sufficient parts of the `sklearn` interface - like `CatBoostRegressor` - this leads to a crash instead of working.

This case was also not tested, because all tests assume either total non-conformance with `sklearn` or total conformance.

**Comment by fkiraly** [comment]
Ouch, `catboost` seems `sklearn` incompatible to a high degree, from the tests in the PR that checks a composite estimator with a `catboost` instance in it:

```
FAILED sktime/tests/test_all_estimators.py::TestAllObjects::test_set_params[DirectReductionForecaster-5] - _catboost.CatBoostError: The left argument is not fitted, only fitted models could be compared.
FAILED sktime/tests/test_all_estimators.py::TestAllObjects::test_set_params_sklearn[DirectReductionForecaster] - _catboost.CatBoostError: The left argument is not fitted, only fitted models could be compared.
FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllObjects::test_set_params[DirectReductionForecaster-5] - _catboost.CatBoostError: The left argument is not fitted, only fitted models could be compared.
FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllObjects::test_set_params_sklearn[DirectReductionForecaster] - _catboost.CatBoostError: The left argument is not fitted, only fitted models could be compared.
```

**Comment by fkiraly** [comment]
... one could almos targue that the inference logic is correct in this case, or should say at least, dear user, use at your own risk...
