### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bastisar** [sktime/sktime#7100]
**Describe the bug**
(Still experimental) `RecursiveReductionForecaster` fails for hierachical (i.e. with instances and time indexes) data with global approach. Returns: `TypeError: Cannot convert input [('xxx', Period('2017-02', 'M'))] of type <class 'tuple'> to Timestamp`

**To Reproduce**
Run tests for PR https://github.com/sktime/sktime/pull/4806

**Expected behavior**
`RecursiveReductionForecaster` should be able to correctly identify cohorts in the hierarchy to use global approach

**Additional context**
Error seems to rise from `_predict_out_of_sample()` where we try to convert the index https://github.com/sktime/sktime/blob/e4d60d1f539cc5f5f4e4054266b9f7db4cf321c1/sktime/forecasting/compose/_reduce.py#L2501) but that fails obvisouly for multiindex:

```python
if hasattr(self.fh, "freq") and self.fh.freq is not None:
   y_plus_preds = y_plus_preds.asfreq(self.fh.freq)
```

See also discord discussion: https://discord.com/channels/1075852648688930887/1277878516490178641

**Versions**
<details>

System:
    python: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
executable: .../venv/bin/python
   machine: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

Python dependencies:
          pip: 24.2
       sktime: 0.32.0
      sklearn: 1.2.2
       skbase: 0.8.3
        numpy: 1.23.5
        scipy: 1.14.1
       pandas: 1.5.3
   matplotlib: 3.9.2
       joblib: 1.3.2
        numba: 0.60.0
  statsmodels: 0.14.2
     pmdarima: 2.0.4
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None

</details>

**Comment by fkiraly** [comment]
@bastisar, it seems the `RecursiveReductionForecaster` no longer fails tests for hierarchical data.

Perhaps this PR fixed it?
https://github.com/sktime/sktime/pull/7172

Is this plausible, @tianjiqx?

**Comment by tianjiqx** [comment]
> @bastisar, it seems the `RecursiveReductionForecaster` no longer fails tests for hierarchical data.，则 `RecursiveReductionForecaster` 似乎不再无法通过分层数据的测试。
> 
> Perhaps this PR fixed it?也许这个 PR 解决了它？ #7172
> 
> Is this plausible, @tianjiqx? 这合理吗，？

May not be relevant or able to resolve? The previous pr #7172 addressed a calculation bug in pandas < 1.5.0, but this issue shows that pandas is already version 1.5.3.

**Comment by lenaklosik** [comment]
Hi everyone,

I tested the described issue using the latest main branch of sktime, and the problems still persist.
(Discussion in Discord: https://discord.com/channels/1075852648688930887/1305813291402133537) 
Here are the details:

# **1. Minimal Reproducible Example**
I created a script that reproduces the issue. It uses RecursiveReductionForecaster (global) in combination with ForecastingOptunaSearchCV and ForecastingGridSearchCV.
I also tested the whole setup with `pooling = "local"`, where everything works as expected.

Here is the whole zip file with the data: 
[RFF_global.zip](https://github.com/user-attachments/files/18037776/RFF_global.zip)

I took the data from this hierarchical Notebook: 
https://github.com/sktime/sktime-tutorial-euroscipy2024/blob/main/notebooks/02_hierarchical_forecasting.ipynb


```python
from sklearn.pipeline import make_pipeline
from sktime.forecasting.compose._reduce import (
    RecursiveReductionForecaster,
)
from xgboost import XGBRegressor
from sktime.forecasting.model_selection import (
    ForecastingGridSearchCV,
    ForecastingOptunaSearchCV,
)
from sktime.performance_metrics.forecasting import MeanAbsoluteError
from sktime.utils.estimator_checks import check_estimator
from sktime.transformations.hierarchical.aggregate import Aggregator
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.split import ExpandingWindowSplitter, SlidingWindowSplitter
import numpy as np

from utils import load_stallion

import optuna

parallel_config = {
    "backend:parallel": "joblib",
    "backend:parallel:params": {"backend": "loky", "n_jobs": -1},  # deactivate parallel here
}

lags = 12

params_xgb = {
    "random_state": 42,
}

regressor = make_pipeline(
    XGBRegressor(**params_xgb),
)

model_xgb = RecursiveReductionForecaster(
    estimator=regressor,
    impute_method="bfill",
    pooling="global",
    window_length=lags,
)

pipe_forecast = model_xgb

# %%
_, y = load_stallion(as_period=True)

# Filter the data to reduce the dataset size
y = y.reset_index()
y = y[y['agency'].str.match(r'Agency_0[1-2]$')]
y = y[y['sku'].str.match(r'SKU_0[1-3]$')]
y = y[y['date'] > '2013-12']
y = y.set_index(["agency", "sku", "date"])
# %%

agg = Aggregator(flatten_single_levels=False)
data_agg = agg.reset().fit_transform(y)

# %%
y_train, y_test = temporal_train_test_split(y, test_size=18)
test_fh = y_test.index.get_level_values(-1).unique()

# %%
parameter_search_space_optuna = {
    "estimator__xgbregressor__n_estimators": optuna.distributions.IntDistribution(10, 3000),
}

parameter_search_space_grid = {
    "estimator__xgbregressor__n_estimators": list(range(10, 3000, 10)),  # grid
}

parameter_search_space_rrf = {
    "forecaster__forecaster__estimator__xgbregressor__n_estimators": optuna.distributions.IntDistribution(10, 3000),
}

fh = 18
fold = 4
step_length=3
y_size = len(y_train.index.get_level_values(-1).unique())
single_fold_length = y_size - (fold - 1) * step_length - fh
fold_strategy =  ExpandingWindowSplitter(
                fh=np.arange(1, fh + 1), initial_window=single_fold_length, step_length=step_length
            )

sampler = optuna.samplers.TPESampler(seed=42)

grid = ForecastingGridSearchCV(
    forecaster=pipe_forecast,
    param_grid=parameter_search_space_grid,
    cv=fold_strategy,
    error_score="raise",
    scoring=MeanAbsoluteError(),
)


htcv = ForecastingOptunaSearchCV(
    forecaster=pipe_forecast,
    param_grid=parameter_search_space_optuna,
    cv=fold_strategy,
    n_evals=5,
    scoring=MeanAbsoluteError(),
    error_score="raise",
    sampler=sampler,
)

# %% [markdown]
# ## Fit

only_rff_xgb_fitted = model_xgb.fit(
    y=y_train,
    fh=test_fh,
)

optuna_fitted = htcv.fit(
    y=y_train,
    fh=test_fh,
)

grid_fitted = grid.fit(
    y=y_train,
    fh=test_fh,
)

# ## predict
only_rff_xgb_fitted.predict(fh=test_fh)


``` 


# 2. Observed Issues

**Only XGBoost, RecursiveReductionForecaster (global):**
- calling `.fit()`:  works
- calling `.predict()`: `Error: TypeError: Cannot convert input [('Agency_01', 'SKU_01', Period('2013-01', 'M'))] of type <class 'tuple'> to Timestamp`

**XGBoost, RecursiveReductionForecaster (global) with ForecastingOptunaSearchCV:**
- calling `.fit()`:  `Error: TypeError: Cannot convert input [('Agency_01', 'SKU_01', Period('2013-01', 'M'))] of type <class 'tuple'> to Timestamp`

**XGBoost, RecursiveReductionForecaster (global) with ForecastingGridSearchCV:**
- calling `.fit()`:  `Error: TypeError: Cannot convert input [('Agency_01', 'SKU_01', Period('2013-01', 'M'))] of type <class 'tuple'> to Timestamp`

# 3. Check-Estimator Output
The results from running check_estimator() are:

**3.1 check_estimator(model_xgb) (Only XGBoost, RecursiveReductionForecaster (global)):** 

- FAILED: test_hierarchical_with_exogeneous[RecursiveReductionForecaster-y:1cols]
- FAILED: test_hierarchical_with_exogeneous[RecursiveReductionForecaster-y:2cols]

**3.2 check_estimator(grid) (ForecastingGridSearchCV (global)):**

```python
File "/xxx/lib/python3.10/site-packages/sktime/forecasting/model_selection/_tune.py", line 552, in NoName
Failed example:
    gscv.fit(y)
Expected:
    ForecastingGridSearchCV(...)
Got:
    ForecastingGridSearchCV(cv=ExpandingWindowSplitter(fh=[1, 2, 3]),
                            forecaster=NaiveForecaster(),
                            param_grid={'strategy': ['last', 'mean', 'drift']})
```

**3.3 check_estimator(htcv) (ForecastingOptunaSearchCV (global)):**
-> Keyboardinterrupt after 1 hour runtime
```python

File "/xxx/lib/python3.10/site-packages/sktime/forecasting/model_selection/_tune.py", line 1697, in NoName
Failed example:
    fh = ForecastingHorizon(y_test.index, is_relative=False).to_relative(
Exception raised:
    Traceback (most recent call last):
      File "/xxx/.pyenv/versions/3.10.6/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[18]>", line 1
        fh = ForecastingHorizon(y_test.index, is_relative=False).to_relative(
                                                                            ^
    SyntaxError: '(' was never closed
**********************************************************************
File "/xxx/lib/python3.10/site-packages/sktime/forecasting/model_selection/_tune.py", line 1698, in NoName
Failed example:
    cutoff=y_train.index[-1]
        )
Exception raised:
    Traceback (most recent call last):
      File "/xxx/.pyenv/versions/3.10.6/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[19]>", line 1
        cutoff=y_train.index[-1]
                                ^
    SyntaxError: multiple statements found while compiling a single statement
**********************************************************************
File /xxx/lib/python3.10/site-packages/sktime/forecasting/model_selection/_tune.py", line 1700, in NoName
Failed example:
    cv = ExpandingWindowSplitter(fh=fh, initial_window=24, step_length=1)
Exception raised:
    Traceback (most recent call last):
      File "/xxx/.pyenv/versions/3.10.6/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[20]>", line 1, in <module>
        cv = ExpandingWindowSplitter(fh=fh, initial_window=24, step_length=1)
    NameError: name 'fh' is not defined
**********************************************************************
File "/xxx/lib/python3.10/site-packages/sktime/forecasting/model_selection/_tune.py", line 1701, in NoName
Failed example:
    forecaster = TransformedTargetForecaster(
Exception raised:
    Traceback (most recent call last):
      File "/xxx/.pyenv/versions/3.10.6/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[21]>", line 1
        forecaster = TransformedTargetForecaster(
                                                ^
    SyntaxError: '(' was never closed
**********************************************************************
File "/xxx/lib/python3.10/site-packages/sktime/forecasting/model_selection/_tune.py", line 1702, in NoName
Failed example:
    steps=[
        ("detrender", Detrender()),
        ("deseasonalizer", Deseasonalizer()),
        ("scaler", TabularToSeriesAdaptor(RobustScaler())),
        ("minmax2", TabularToSeriesAdaptor(MinMaxScaler((1, 10)))),
        ("forecaster", NaiveForecaster()),
        ]
        )
Exception raised:
    Traceback (most recent call last):
      File "/xxx/.pyenv/versions/3.10.6/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[22]>", line 7
        ]
         ^
    SyntaxError: multiple statements found while compiling a single statement
**********************************************************************
File "/xxx/lib/python3.10/site-packages/sktime/forecasting/model_selection/_tune.py", line 1710, in NoName
Failed example:
    param_grid = {
        "scaler__transformer__with_scaling": CategoricalDistribution(
             (True, False)
        ),
Exception raised:
    Traceback (most recent call last):
      File "/xxx/.pyenv/versions/3.10.6/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[23]>", line 1
        param_grid = {
                     ^
    SyntaxError: '{' was never closed
**********************************************************************
File "/xxx/lib/python3.10/site-packages/sktime/forecasting/model_selection/_tune.py", line 1718, in NoName
Failed example:
    gscv = ForecastingOptunaSearchCV(
        forecaster=forecaster,
        param_grid=param_grid,
        cv=cv,
        n_evals=10,
        )
Exception raised:
    Traceback (most recent call last):
      File "/xxx/.pyenv/versions/3.10.6/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[24]>", line 2, in <module>
        forecaster=forecaster,
    NameError: name 'forecaster' is not defined. Did you mean: 'STLForecaster'?
**********************************************************************
File "/xxx/lib/python3.10/site-packages/sktime/forecasting/model_selection/_tune.py", line 1724, in NoName
Failed example:
    gscv.fit(y)
Exception raised:
    Traceback (most recent call last):
      File "/xxx/.pyenv/versions/3.10.6/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[25]>", line 1, in <module>
        gscv.fit(y)
    NameError: name 'gscv' is not defined
**********************************************************************
File "/xxx/lib/python3.10/site-packages/sktime/forecasting/model_selection/_tune.py", line 1725, in NoName
Failed example:
    print(f"{gscv.best_params_=}")
Exception raised:
    Traceback (most recent call last):
      File "/xxx/.pyenv/versions/3.10.6/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest NoName[26]>", line 1, in <module>
        print(f"{gscv.best_params_=}")
    NameError: name 'gscv' is not defined
``` 


# 4. System and Version Information
Here is the output of show_versions():
```python
/xxx/xxx/xxx/xxx/lib/python3.10/site-packages/_distutils_hack/__init__.py:31: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(

INSTALLED VERSIONS
------------------
commit           : xxx
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.153.1-microsoft-standard-WSL2
Version          : #1 SMP Fri Mar 29 23:14:13 UTC 2024
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.23.5
pytz             : 2024.2
dateutil         : 2.9.0.post0
setuptools       : 75.1.0
pip              : 24.2
Cython           : 3.0.11
pytest           : 7.4.2
hypothesis       : 6.112.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.4
IPython          : 8.27.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2024.9.0
gcsfs            : None
matplotlib       : 3.9.2
numba            : 0.60.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 17.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.14.1
snappy           : None
sqlalchemy       : 2.0.34
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

```

**Comment by bastisar** [comment]
@fkiraly, @lenaklosik just for my understanding, that means, the test are not failing anymore, but the error is still existing? So guess we should add a test for that failure and then make it disappear, correct?

**Comment by fkiraly** [comment]
> @fkiraly, @lenaklosik just for my understanding, that means, the test are not failing anymore, but the error is still existing? So guess we should add a test for that failure and then make it disappear, correct?

Yes, indeed.

**Comment by Sohaib-Ahmed21** [comment]
Another issue occurs when **type** of `y.index` in `RecursiveReductionForecaster `is `PeriodIndex` with **yearly** frequency,  in same line i.e.
```python
if hasattr(self.fh, "freq") and self.fh.freq is not None:
   y_plus_preds = y_plus_preds.asfreq(self.fh.freq)
```
The problem is that the frequency of `ForecastingHorizon` Object _(in case of code given below)_ is set in https://github.com/sktime/sktime/blob/main/sktime/forecasting/base/_fh.py as 
```python
with _suppress_pd22_warning:
   offset = to_offset(obj)
```

called from `@freq.setter` as
```python 
freq_from_obj = _check_freq(obj)
``` 



The `to_offset `method from `pandas.tseries.frequencies` here returns **<YearEnd: month=12>** and we finally get freq = **YE-DEC** as we get frequency by `to_offset("Y-DEC").freqstr` and thus, the frequency i.e. `self.fh.freq` is adjusted as **YE-DEC** through **to_offset**. But when `y_plus_preds.asfreq(self.fh.freq)` is called, it gives us following output in terminal:

```
D:\PROGRAMMING\sktime\sktime\sktime\forecasting\base\_fh.py:177: FutureWarning: 'Y-DEC' is deprecated and will be removed in a future version, please use 'YE-DEC' instead.
Traceback (most recent call last):
  File "d:\PROGRAMMING\sktime\sktime\sktime\forecasting\compose\test.py", line 119, in <module>
    y_pred = forecaster.predict(fh, X=X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PROGRAMMING\sktime\sktime\sktime\forecasting\base\_base.py", line 457, in predict
    y_pred = self._predict(fh=fh, X=X_inner)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PROGRAMMING\sktime\sktime\sktime\forecasting\compose\_reduce.py", line 2464, in _predict
    y_pred = self._predict_out_of_sample(X_pool, fh_oos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PROGRAMMING\sktime\sktime\sktime\forecasting\compose\_reduce.py", line 2503, in _predict_out_of_sample
    y_plus_preds = y_plus_preds.asfreq(self.fh.freq)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PROGRAMMING\sktime\sktime\myenv\Lib\site-packages\pandas\core\generic.py", line 9231, in asfreq
    return asfreq(
           ^^^^^^^
  File "D:\PROGRAMMING\sktime\sktime\myenv\Lib\site-packages\pandas\core\resample.py", line 2824, in asfreq
    new_obj.index = obj.index.asfreq(freq, how=how)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PROGRAMMING\sktime\sktime\myenv\Lib\site-packages\pandas\core\indexes\period.py", line 208, in asfreq
    arr = self._data.asfreq(freq, how)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PROGRAMMING\sktime\sktime\myenv\Lib\site-packages\pandas\core\arrays\period.py", line 743, in asfreq
    freq = Period._maybe_convert_freq(freq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "period.pyx", line 1765, in pandas._libs.tslibs.period._Period._maybe_convert_freq
  File "offsets.pyx", line 4954, in pandas._libs.tslibs.offsets.to_offset
ValueError: Invalid frequency: YE-DEC, failed to parse with error message: ValueError("for Period, please use 'Y-DEC' instead of 'YE-DEC'")
```
 Thus, `to_offset` converts **Y-DEC** to **<YearEnd: month=12>** and gives us **YE-DEC** as freq on accessing its freq_str attribute. When trying to apply same freq on `y_plus_preds`, it gives `ValueError("for Period, please use 'Y-DEC' instead of 'YE-DEC'")`.

**Minimal Reproducible code:**
```python
from sktime.forecasting.base import ForecastingHorizon
from sktime.datasets import load_longley
from sktime.forecasting.compose import RecursiveReductionForecaster
from sklearn.linear_model import LinearRegression

# Load the Tecator dataset
y, X = load_longley()

# Define forecasting horizon
fh = ForecastingHorizon([1,2,3,4])  # Forecast next 3 steps

# Define a regressor
regressor = LinearRegression()

# Create the RecursiveReductionForecaster
forecaster = RecursiveReductionForecaster(
    estimator=regressor,
    window_length=2,  # Use past 2 observations for forecasting
)

# Fit the forecaster on training data
forecaster.fit(y=y, X=X, fh=fh)
fh = ForecastingHorizon([1,2,3,4],freq="Y-DEC")  # Forecast next 3 steps
# Predict using the testing exogenous features
y_pred = forecaster.predict(fh, X=X)
print("y_pred", y_pred)
```

**Comment by benHeid** [comment]
This error still exists in the tests see:

```python
from sktime.forecasting.compose._reduce import RecursiveReductionForecaster
from sktime.utils.estimator_checks import check_estimator

check_estimator(RecursiveReductionForecaster, tests_to_run=["test_hierarchical_with_exogeneous"], raise_exceptions=True)
```

or here in the CI: https://github.com/sktime/sktime/actions/runs/13343842205/job/37273891325?pr=7123
