### ISSUE TITLE
[BUG] ClaSPSegmentation giving "ValueError: could not broadcast input array from shape (2,) into shape (3,)"

### ISSUE THREAD

**Issue by ari62** [sktime/sktime#7329]
**Describe the bug**
ClaSPSegmentation  is giving "ValueError: could not broadcast input array from shape (2,) into shape (3,)".

Either increasing the period_length or decreasing exclusion radius seems to encourage the error.

`clasp = ClaSPSegmentation(period_length=10, n_cps=2000, exclusion_radius=.0001)
`
The full stack trace is:
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[11], line 5
      1 # 
      2 # going to a smaller exclusion radius gives ValueError: could not broadcast input array from shape (2,) into shape (3,)
      3 # timesing the ts by 100 and raising the exclusion radius doesnt help. ALSO making the period size from 10 to 20 causes the error. IT IS TOO CONFUSING and risky
      4 clasp = ClaSPSegmentation(period_length=period_size, n_cps=2000, exclusion_radius=.0001)
----> 5 found_cps = clasp.fit_predict(ts)
      6 profiles = clasp.profiles
      7 scores = clasp.scores

File ~/PycharmProjects/sktime_stuff/sktime_venv/lib/python3.12/site-packages/sktime/annotation/base/_base.py:291, in BaseSeriesAnnotator.fit_predict(self, X, Y)
    272 """Fit to data, then predict it.
    273 
    274 Fits model to X and Y with given annotation parameters
   (...)
    287     Annotations for sequence X exact format depends on annotation type.
    288 """
    289 # Non-optimized default implementation; override when a better
    290 # method is possible for a given algorithm.
--> 291 return self.fit(X, Y).predict(X)

File ~/PycharmProjects/sktime_stuff/sktime_venv/lib/python3.12/site-packages/sktime/annotation/base/_base.py:174, in BaseSeriesAnnotator.predict(self, X)
    170 X = check_series(X)
    172 # fkiraly: insert checks/conversions here, after PR #1012 I suggest
--> 174 Y = self._predict(X=X)
    176 return Y

File ~/PycharmProjects/sktime_stuff/sktime_venv/lib/python3.12/site-packages/sktime/annotation/clasp.py:263, in ClaSPSegmentation._predict(self, X)
    250 def _predict(self, X):
    251     """Create annotations on test/deployment data.
    252 
    253     Parameters
   (...)
    261         Change points in sequence X.
    262     """
--> 263     change_points = self._predict_points(X)
    264     if self._fmt == "dense":
    265         return self.change_points_to_segments(
    266             change_points, X.index.min(), X.index.max()
    267         )

File ~/PycharmProjects/sktime_stuff/sktime_venv/lib/python3.12/site-packages/sktime/annotation/clasp.py:283, in ClaSPSegmentation._predict_points(self, X)
    270 def _predict_points(self, X):
    271     """Predict changepoints on test/deployment data.
    272 
    273     Parameters
   (...)
    281         Series containing the indexes of the changepoints in X.
    282     """
--> 283     self.found_cps, self.profiles, self.scores = self._run_clasp(X)
    284     return pd.Series(self.found_cps)

File ~/PycharmProjects/sktime_stuff/sktime_venv/lib/python3.12/site-packages/sktime/annotation/clasp.py:330, in ClaSPSegmentation._run_clasp(self, X)
    324     X = X.to_numpy()
    326 clasp_transformer = ClaSPTransformer(
    327     window_length=self.period_length, exclusion_radius=self.exclusion_radius
    328 ).fit(X)
--> 330 self.found_cps, self.profiles, self.scores = _segmentation(
    331     X,
    332     clasp_transformer,
    333     n_change_points=self.n_cps,
    334     exclusion_radius=self.exclusion_radius,
    335 )
    337 return self.found_cps, self.profiles, self.scores

File ~/PycharmProjects/sktime_stuff/sktime_venv/lib/python3.12/site-packages/sktime/annotation/clasp.py:154, in _segmentation(X, clasp, n_change_points, exclusion_radius)
    151 for ranges in [left_range, right_range]:
    152     # create and enqueue left local profile
    153     if len(ranges) > period_size:
--> 154         profile = clasp.transform(X[ranges])
    155         change_point = np.argmax(profile)
    156         score = profile[change_point]

File ~/PycharmProjects/sktime_stuff/sktime_venv/lib/python3.12/site-packages/sktime/transformations/base.py:623, in BaseTransformer.transform(self, X, y)
    621 # if no vectorization needed, we call _transform directly
    622 if not vectorization_needed:
--> 623     Xt = self._transform(X=X_inner, y=y_inner)
    624 else:
    625     # otherwise we call the vectorized version of predict
    626     Xt = self._vectorize("transform", X=X_inner, y=y_inner)

File ~/PycharmProjects/sktime_stuff/sktime_venv/lib/python3.12/site-packages/sktime/transformations/series/clasp.py:112, in ClaSPTransformer._transform(self, X, y)
    109 scoring_metric_call = self._check_scoring_metric(self.scoring_metric)
    111 X = X.flatten()
--> 112 Xt, _ = clasp(
    113     X,
    114     self.window_length,
    115     score=scoring_metric_call,
    116     exclusion_radius=self.exclusion_radius,
    117 )
    119 return Xt

File ~/PycharmProjects/sktime_stuff/sktime_venv/lib/python3.12/site-packages/sktime/transformations/series/_clasp_numba.py:329, in clasp(X, m, k_neighbours, score, interpolate, exclusion_radius)
    299 def clasp(
    300     X,
    301     m,
   (...)
    305     exclusion_radius=0.05,
    306 ):
    307     """Calculate ClaSP for a time series and a window size.
    308 
    309     Parameters
   (...)
    327         The ClaSP and the knn_mask
    328     """
--> 329     knn_mask = _compute_distances_iterative(X, m, k_neighbours).T
    331     n_timepoints = knn_mask.shape[1]
    332     exclusion_radius = np.int64(n_timepoints * exclusion_radius)

File ~/PycharmProjects/sktime_stuff/sktime_venv/lib/python3.12/site-packages/sktime/transformations/series/_clasp_numba.py:116, in _compute_distances_iterative(X, m, k)
    113     _k = min(k, len(dist) - 1)
    114     idx = np.argpartition(dist, _k)
--> 116     knns[order, :] = idx[:k]
    117     dot_prev = dot_rolled
    119 return knns

ValueError: could not broadcast input array from shape (2,) into shape (3,)

```
**To Reproduce**
series.csv is here:
[series.csv](https://github.com/user-attachments/files/17499223/series.csv)

```python
#%%
from sktime.annotation.clasp import ClaSPSegmentation
import numpy as np
import pandas as pd


df = pd.read_csv('series.csv', index_col=0)
df.index = pd.to_datetime(df.index)
ts = df.iloc[:, 0]


clasp = ClaSPSegmentation(period_length=10, n_cps=2000, exclusion_radius=.0001)
found_cps = clasp.fit_predict(ts)

```

**Expected behavior**
No error is produced and the results are returned.

**Versions**
<details>

System:
    python: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ]
executable: /Users/user/PycharmProjects/sktime_stuff/sktime_venv/bin/python
   machine: macOS-15.0.1-arm64-arm-64bit

Python dependencies:
          pip: 24.2
       sktime: 0.34.0
      sklearn: 1.5.2
       skbase: 0.8.3
        numpy: 1.26.4
        scipy: 1.14.1
       pandas: 2.2.3
   matplotlib: 3.9.2
       joblib: 1.4.2
        numba: 0.60.0
  statsmodels: 0.14.4
     pmdarima: 2.0.4
statsforecast: 1.7.8
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None

</details>

**Comment by fkiraly** [comment]
FYI @Alex-JG3, I think you refactored it recently.

I see the PR with the interface tests is not merged yet, would this resolve the bug?

**Comment by Alex-JG3** [comment]
I have just ran @ari62's example from the main branch and got the same error. Here is the script, I shortened `ts` for speed.

```
#%%
from sktime.annotation.clasp import ClaSPSegmentation
import numpy as np
import pandas as pd

df = pd.read_csv('series.csv', index_col=0)
df.index = pd.to_datetime(df.index)
ts = df.iloc[:, 0]

clasp = ClaSPSegmentation(period_length=10, n_cps=2000, exclusion_radius=.0001)
found_cps = clasp.fit_predict(ts)
```

Here is the error message.

```
Traceback (most recent call last):
  File "/home/alex/documents/sktime/test.py", line 9, in <module>
    found_cps = clasp.fit_predict(ts)
  File "/home/alex/documents/sktime/sktime/detection/base/_base.py", line 407, in fit_predict
    return self.fit(X, y=y, Y=Y).predict(X)
  File "/home/alex/documents/sktime/sktime/detection/base/_base.py", line 229, in predict
    y = self._predict(X=X_inner)
  File "/home/alex/documents/sktime/sktime/detection/clasp.py", line 261, in _predict
    self.found_cps, self.profiles, self.scores = self._run_clasp(X)
  File "/home/alex/documents/sktime/sktime/detection/clasp.py", line 322, in _run_clasp
    self.found_cps, self.profiles, self.scores = _segmentation(
  File "/home/alex/documents/sktime/sktime/detection/clasp.py", line 154, in _segmentation
    profile = clasp.transform(X[ranges])
  File "/home/alex/documents/sktime/sktime/transformations/base.py", line 623, in transform
    Xt = self._transform(X=X_inner, y=y_inner)
  File "/home/alex/documents/sktime/sktime/transformations/series/clasp.py", line 112, in _transform
    Xt, _ = clasp(
  File "/home/alex/documents/sktime/sktime/transformations/series/_clasp_numba.py", line 329, in clasp
    knn_mask = _compute_distances_iterative(X, m, k_neighbours).T
  File "/home/alex/documents/sktime/sktime/transformations/series/_clasp_numba.py", line 116, in _compute_distances_iterative
    knns[order, :] = idx[:k]
ValueError: could not broadcast input array from shape (2,) into shape (3,)
```

**Comment by Alex-JG3** [comment]
The problem looks like it is in `sktime/transformations/series/_clasp_numba.py` in the `_compute_distances_iterative` method which is called inside the `clasp` method of the same module.

Here is an minimal call to `_compute_distances_iterative` that fails in the same as before.

```python
from sktime.transformations.series._clasp_numba import _compute_distances_iterative

x = np.asarray(
    [-0.00046711, -0.00680347, -0.00014258, -0.01502704,  0.00428476,
    0.00024579,  0.00360899,  0.00174397,  0.00706988,  0.00103107, 0.00049927]
)
window_length = 10
exclusion_radius = 0.0001

# k=3 is the default value from the `clasp` method.
_compute_distances_iterative(x, m=window_length, k=3)
```

**Comment by Alex-JG3** [comment]
After a little more exploration, it appears that `ClaSPSegmentation` fails when `_compute_distances_iterative` is called on an `m` (window size)  that is 1 more than the length of `X`.

I added the following print statement at the start of `_compute_distances_iterative`:

```python
print(f"len(X): {len(X)},  m: {m}, k: {k}")
```
And ran the following script:

```python
# test.py
from sktime.detection.clasp import ClaSPSegmentation
import numpy as np

x = np.array([0.5] * 100)
clasp = ClaSPSegmentation(period_length=10, n_cps=20, exclusion_radius=.0001)
clasp.fit(x)
clasp.transform(x)
```

Here is the resulting error:

```python
$ python3 test.py
len(X): 100,  m: 10, k: 3
len(X): 90,  m: 10, k: 3
len(X): 80,  m: 10, k: 3
len(X): 70,  m: 10, k: 3
len(X): 60,  m: 10, k: 3
len(X): 50,  m: 10, k: 3
len(X): 40,  m: 10, k: 3
len(X): 30,  m: 10, k: 3
len(X): 20,  m: 10, k: 3
len(X): 19,  m: 10, k: 3
len(X): 18,  m: 10, k: 3
len(X): 17,  m: 10, k: 3
len(X): 16,  m: 10, k: 3
len(X): 15,  m: 10, k: 3
len(X): 14,  m: 10, k: 3
len(X): 13,  m: 10, k: 3
len(X): 12,  m: 10, k: 3
len(X): 11,  m: 10, k: 3
Traceback (most recent call last):
  File "/home/alex/documents/sktime/test.py", line 45, in <module>
    clasp.transform(x)
  File "/home/alex/documents/sktime/sktime/detection/base/_base.py", line 260, in transform
    y = self.predict(X)
  File "/home/alex/documents/sktime/sktime/detection/base/_base.py", line 230, in predict
    y = self._predict(X=X_inner)
  File "/home/alex/documents/sktime/sktime/detection/clasp.py", line 261, in _predict
    self.found_cps, self.profiles, self.scores = self._run_clasp(X)
  File "/home/alex/documents/sktime/sktime/detection/clasp.py", line 322, in _run_clasp
    self.found_cps, self.profiles, self.scores = _segmentation(
  File "/home/alex/documents/sktime/sktime/detection/clasp.py", line 154, in _segmentation
    profile = clasp.transform(X[ranges])
  File "/home/alex/documents/sktime/sktime/transformations/base.py", line 623, in transform
    Xt = self._transform(X=X_inner, y=y_inner)
  File "/home/alex/documents/sktime/sktime/transformations/series/clasp.py", line 112, in _transform
    Xt, _ = clasp(
  File "/home/alex/documents/sktime/sktime/transformations/series/_clasp_numba.py", line 333, in clasp
    knn_mask = _compute_distances_iterative(X, m, k_neighbours).T
  File "/home/alex/documents/sktime/sktime/transformations/series/_clasp_numba.py", line 120, in _compute_distances_iterative
    knns[order, :] = idx[:k]
ValueError: could not broadcast input array from shape (2,) into shape (3,)
```

So, error is raise in `_compute_distances_iterative` when the `X` passed to that method has a length one more than the window size.

I not too familiar with `ClaSPSegmentation` so I am not sure why exactly this distance is being calculated.
