### ISSUE TITLE
[BUG] Problem with tuning multioutput regressor with `fh`

### ISSUE THREAD

**Issue by j-adamczyk** [sktime/sktime#7360]
**Describe the bug**

I'm trying to do a pretty standard temporal train-valid split and hyperparameter tuning:
```
from sklearn.linear_model import LinearRegression
from sktime.forecasting.compose import MultioutputTabularRegressionForecaster
from sktime.forecasting.model_selection import ForecastingGridSearchCV
from sktime.performance_metrics.forecasting import (
    mean_absolute_scaled_error,
    MeanAbsoluteScaledError
)
from sktime.split import TemporalTrainTestSplitter


def evaluate_linear_regression(df_train: pd.DataFrame, df_test: pd.DataFrame) -> None:
    lin_reg = MultioutputTabularRegressionForecaster(LinearRegression())
    cv = ForecastingGridSearchCV(
        forecaster=lin_reg,
        cv=TemporalTrainTestSplitter(test_size=0.2),
        param_grid={"window_length": [24, 48, 72, 96, 120, 144, 168, 192, 336, 504, 672, 720]},
        scoring=MeanAbsoluteScaledError(),
        error_score="raise",
    )
    
    cv.fit(df_train, fh=len(df_test))
    
    y_pred = lin_reg.predict()
    mase = mean_absolute_scaled_error(df_test, y_pred, y_train=df_train)

    print(f"MASE linear regression: {mase:.2f}")

```

I get an error:
```python
Traceback (most recent call last):
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/sktime/forecasting/model_selection/_tune.py", line 371, in _fit_and_score
    out = evaluate(forecaster, **meta)
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/sktime/forecasting/model_evaluation/_functions.py", line 612, in evaluate
    results = parallelize(
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/sktime/utils/parallel.py", line 72, in parallelize
    ret = para_fun(
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/sktime/utils/parallel.py", line 92, in _parallelize_none
    ret = [fun(x, meta=meta) for x in iter]
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/sktime/utils/parallel.py", line 92, in <listcomp>
    ret = [fun(x, meta=meta) for x in iter]
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/sktime/forecasting/model_evaluation/_functions.py", line 270, in _evaluate_window
    raise e
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/sktime/forecasting/model_evaluation/_functions.py", line 262, in _evaluate_window
    score = metric(y_test, y_pred, y_train=y_train)
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/sktime/performance_metrics/forecasting/_classes.py", line 220, in __call__
    return self.evaluate(y_true, y_pred, **kwargs)
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/sktime/performance_metrics/forecasting/_classes.py", line 300, in evaluate
    y_true_inner, y_pred_inner, multioutput, multilevel, kwargs = self._check_ys(
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/sktime/performance_metrics/forecasting/_classes.py", line 692, in _check_ys
    y_true, y_pred, multioutput, multilevel = self._check_consistent_input(
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/lib/python3.10/site-packages/sktime/performance_metrics/forecasting/_classes.py", line 596, in _check_consistent_input
    raise ValueError("y_pred and y_true do not have the same number of rows.")
ValueError: y_pred and y_true do not have the same number of rows.
```

I tried passing different `fh` to `.fit()`, splitting manually etc., and I always get that error.

**Expected behavior**

Providing `fh` should not be necessary at all, since I'm explicitly using a splitter and grid search CV. As such, `fh` can be explicitly extracted after train-valid split inside.

Apart from that, I would appreciate help, or maybe an example in the docs? The main problem is that this particular forecaster requires passing `fh` to `.fit()` - all simpler cases worked flawlessly.

**Versions**

System:
    python: 3.10.15 (main, Sep  7 2024, 18:35:38) [GCC 13.2.0]
executable: /home/jakub/.cache/pypoetry/virtualenvs/ml-time-series-forecasting-course-solution-27NYmbH6-py3.10/bin/python
   machine: Linux-6.8.0-48-generic-x86_64-with-glibc2.39
Python dependencies:
          pip: 24.1
       sktime: 0.34.0
      sklearn: 1.5.2
       skbase: 0.11.0
        numpy: 2.0.2
        scipy: 1.14.1
       pandas: 2.2.3
   matplotlib: 3.9.2
       joblib: 1.4.2
        numba: 0.60.0
  statsmodels: 0.14.4
     pmdarima: 2.0.4
statsforecast: 1.7.8
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None

**Comment by manshirahangdale** [comment]
This appears to be a framework-level bug rather than user error.
During ForecastingGridSearchCV, fh is not aligned with the test window produced by the splitter for reduction-based forecasters that require fh at fit time (e.g. MultioutputTabularRegressionForecaster).
that results,  y_pred and y_true have mismatched lengths during scoring .
Likely fix: derive fh per CV split from y_test and pass it into fit/predict inside _evaluate_window.
Happy to open a PR—please let me know preferred direction.
