### ISSUE TITLE
[ENH] Support for NumPy Array Input in segments_to_change_points

### ISSUE THREAD

**Issue by Spinachboul** [sktime/sktime#7490]
I want to highlight a potential enhancement to the `segments_to_change_points` function. Currently, the function is tested with sparse segments represented as a **Pandas Series** (with an `IntervalIndex`). However, there is no coverage for sparse segments represented as **NumPy arrays**.  

### Context  
Here’s an example of how sparse segments are currently represented as a Pandas Series:  
```python
import pandas as pd

sparse_segments = pd.Series(
    [1, -1, 2],
    index=pd.IntervalIndex.from_breaks([2, 5, 7, 9], closed="left"),
)
print(sparse_segments)

# Output:
# [2, 5)    1
# [5, 7)   -1
# [7, 9)    2
# dtype: int64
```

To represent the same data in a **NumPy array**, we could use a 2D array:  
```python
sparse_segments_numpy = [
    [2, 5, 1],   # Interval [2, 5) with value 1
    [5, 7, -1],  # Interval [5, 7) with value -1
    [7, 9, 2],   # Interval [7, 9) with value 2
]
```

### Proposed Change  
We should extend `segments_to_change_points` to support NumPy arrays as input. This would involve:  
1. Adding functionality to process NumPy arrays structured as described above.  
2. Ensuring the function handles edge cases, such as negative values in the labels.  

### Next Steps  
- Write new test cases for `segments_to_change_points` that cover NumPy array inputs.  
- Decide the best representation and conventions for sparse segments as NumPy arrays.  
- Discuss whether this change aligns with the design principles of the library.  

### References  
This enhancement was initially discussed in relation to https://github.com/sktime/sktime/pull/7472 for better visibility and collaboration.

**Comment by satvshr** [comment]
I picked this issue up but when I ran the text code mentioned in the functions doc:
```
import pandas as pd
from sktime.detection.base import BaseDetector
segments = pd.Series(
    [3, -1, 2], index=pd.IntervalIndex.from_breaks([2, 5, 7, 9], closed="left"), dtype=int)

BaseDetector.segments_to_change_points(segments)
```
it threw an error:
```
Traceback (most recent call last):
  File "C:\Users\satvm\sktime\test.py", line 6, in <module>
    BaseDetector.segments_to_change_points(segments)
  File "C:\Users\satvm\sktime\sktime\detection\base\_base.py", line 1188, in segments_to_change_points
    change_points = y_sparse.set_index("ilocs").index.left
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\satvm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Series' object has no attribute 'set_index'. Did you mean: 'reset_index'?
```
I opened the reference issue mentioned above and even though there is a test for this [function](https://github.com/sktime/sktime/blob/cc1f7bdc20fecfd91aad5339b88fa8ae4d463109/sktime/detection/tests/test_base.py#L137), it is not failing for some reason?

**Comment by satvshr** [comment]
The docstring also says that we have to return a Series object but `_empty_sparse` returns a dataframe.
Moreover why do we even need `test_segments_to_change_points` when [_coerce_to_df](https://github.com/sktime/sktime/blob/cc1f7bdc20fecfd91aad5339b88fa8ae4d463109/sktime/detection/base/_base.py#L567) can handle "IntervalIndex containing segments"?

**Comment by Spinachboul** [comment]
@satvshr 
Yes!  We need to fix this inconsistency of the return types of different functions. We can maybe internally convert the `Series` format into `Dataframe` so that the `set_index` function could be supported.
Also we need to include acceptance of `numpy` arrays as inputs in the `segments_to_change_points` function

> The docstring also says that we have to return a Series object but `_empty_sparse` returns a dataframe, so does [_empty_segments](https://github.com/sktime/sktime/blob/99a18e61bad502f8b22cddb4e167bd36adbe2098/sktime/detection/base/_base.py#L1078) Moreover why do we even need `test_segments_to_change_points` when [_coerce_to_df](https://github.com/sktime/sktime/blob/cc1f7bdc20fecfd91aad5339b88fa8ae4d463109/sktime/detection/base/_base.py#L567) can handle "IntervalIndex containing segments"? One could say that we need this function for when we want our output to be a Series object and not a dataframe but then again `_empty_sparse` returns a dataframe.

So then we need to convert all the return types to series since

**Comment by satvshr** [comment]
> @satvshr Yes! We need to fix this inconsistency of the return types of different functions. We can maybe internally convert the `Series` format into `Dataframe` so that the `set_index` function could be supported. Also we need to include acceptance of `numpy` arrays as inputs in the `segments_to_change_points` function

What if we remove the `segments_to_change_points` function entirely and just incorporate numpy arrays into `coerce_to_df`?
I'd also like to add that even though the functions mention that they return a `Series` in the docstring, all of them are already returning dataframes. One last question, any idea why the test is passing even though the function does not work?
> I opened the reference issue mentioned above and even though there is a test for this [function](https://github.com/sktime/sktime/blob/cc1f7bdc20fecfd91aad5339b88fa8ae4d463109/sktime/detection/tests/test_base.py#L137), it is not failing for some reason?

**Comment by Spinachboul** [comment]
@satvshr 
Even I am confused as to why the tests were passing earlier, but then the idea of incorporating numpy arrays directly into `_coerce_to_df`  does make sense.
I would guess the original and the modified `_coerce_to_df_`  functions would looks like the following:
<hr>
<b>Original Function</b>

```
if not isinstance(y, (pd.Series, pd.DataFrame)):
    y = pd.DataFrame(y, columns=columns, dtype="int64")
if isinstance(y.index, pd.IntervalIndex):
    if isinstance(y, pd.Series):
        y = pd.DataFrame(y.index, columns=columns)
    elif isinstance(y, pd.DataFrame):
        y_index = y.index
        y_index = pd.DataFrame(y_index, columns=columns)
        y = y.reset_index(drop=True)
        y = pd.concat([y_index, y], axis=1)

if not isinstance(y, pd.DataFrame):
    y = pd.DataFrame(y, columns=columns, dtype="int64")

return y
```

<b>Modified function</b>
```python
if isinstance(y, np.ndarray):
    # Handle NumPy array input: assume format [[start, end, value], ...]
    intervals = pd.IntervalIndex.from_tuples([(row[0], row[1]) for row in y], closed="left")
    y = pd.DataFrame({'intervals': intervals, 'value': [row[2] for row in y]})
elif isinstance(y, pd.Series) and isinstance(y.index, pd.IntervalIndex):
    # Convert Series with IntervalIndex to DataFrame
    y = pd.DataFrame({'intervals': y.index, 'value': y.values})
elif isinstance(y, pd.DataFrame) and isinstance(y.index, pd.IntervalIndex):
    y_index = pd.DataFrame(y.index, columns=columns)
    y = y.reset_index(drop=True)
    y = pd.concat([y_index, y], axis=1)
elif not isinstance(y, pd.DataFrame):
    y = pd.DataFrame(y, columns=columns, dtype="int64")

return y
```
But that said, we can remove the `segments_to_change_points` only after checking any of its references within `_base.py` and other related modules. Also run the tests for that matter

**Comment by Spinachboul** [comment]
@fkiraly 
Could you please give some insights into this discussion?
Thanks!!

**Comment by Spinachboul** [comment]
> Thanks for this discussion! Originally, I did not entirely like that the segments/points conversion functions were public in the first place. I do think that maybe putting a coercion (to df) at the start solves the issues, although this could be fiddly.

Could be fiddly but then ig it needs changes in just  `_base.py` and `test_base.py`
So might be manageable

**Comment by satvshr** [comment]
> But that said, we can remove the segments_to_change_points only after checking any of its references within _base.py and other related modules. Also run the tests for that matter

There is only one other reference of this function, which is then passing the output to coerce_to_df (making it useless anyway).
@fkiraly @Spinachboul should I remove the function, update coerce_to_df, and update the tests for coerce_to_df to include a test case for numpy?

**Comment by satvshr** [comment]
One more doubt, in all cases the columns parameter contains only 1 argument, so should the function be built to accept only 1 argument or should it be able to take arguments of varying sizes? Moreover the function segments_to_change_points mentions converting 
```
[2, 5)    3
[5, 7)   -1
[7, 9)    2
```
to:
```
     col_name
0    2
1    5
2    7
```
Is this the desired output, or is it:
```
    col_name
0  [2, 5)
1  [5, 7)
2  [7, 9)
```

**Comment by satvshr** [comment]
Lastly for a numpy input are we supposed to assume the interval is closed from the left?

**Comment by fkiraly** [comment]
To answer some of the questions:

* the desired output has integers in the `ilocs` columns, not segments
* intervals are assumed closed left

FYI @tveten, @Alex-JG3, if you have any comments

**Comment by satvshr** [comment]
> * the desired output has integers in the `ilocs` columns, not segments

but that's not the output of the current coerce_to_df implementation...... Would you mind giving an example of your desired output?

**Comment by fkiraly** [comment]
> but that's not the output of the current coerce_to_df implementation

I mean, of the conversion function, `segments_to_change_points`

**Comment by satvshr** [comment]
> I mean, of the conversion function, `segments_to_change_points`

yeah but didn't we discuss above that we will just remove that function as it is being used only once before the coerce_to_df function?
