### ISSUE TITLE
Issue with _generate_estimator_instance for [Estimator Name]

### ISSUE THREAD

**Issue by Spinachboul** [sktime/sktime#7503]
@benHeid  @fkiraly  @Alex-JG3 

The test suite fails for `[Estimator Name]` due to an `AttributeError` caused by the absence of a `clone` method in the object generated by `_generate_estimator_instance` in `_conditional_fixtures.py`.

#### Details
- **Error**: `AttributeError: 'SomeObject' object has no attribute 'clone'`.
- **Cause**: `_generate_estimator_instance` does not correctly instantiate `[Estimator Name]`, resulting in an object missing required attributes like `clone`.
- **Impact**: Affects tests for multiple estimators,
[Issue 7414](https://github.com/sktime/sktime/issues/7414)
[Issue 7462](https://github.com/sktime/sktime/issues/7414)

**Comment by fkiraly** [comment]
@Spinachboul, thanks for reporting! Could you kindly provide reproducible instructions to cause the error? What are you trying to do?

Also, what is `SomeObject` - is this a class you created?

**Comment by prajwalsuryawanshi** [comment]
hello @fkiraly , I would like to contribute to this issue but I'm unable to find the `_generate_estimator_instance` in `_conditional_fixtures.py`  am I missing something?

**Comment by Spinachboul** [comment]
@fkiraly 
The issue is all about how we can pass the failing tests for various estimators
Here is an error log as an example for `ClusterSegmenter`

![image](https://github.com/user-attachments/assets/18e1748a-dfec-4835-a960-d70c1f1256e1)

Then here is the example for `GaussianHMM`

![image](https://github.com/user-attachments/assets/e63aeb56-0a76-477b-b1de-620bf7e3987f)

So everytime, the `clone` method is not there for the **static** return types 
So I was wondering if the core devs could work upon this issue and make the return types compatible with `clone()` method.
More specificially , convert them into an object **'someObject'** which does not return attibute error!!

**Comment by fkiraly** [comment]
@Spinachboul, can you kindly do as I request and describe, with code, what you were trying to do here?

See here for a guide how to do this:
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Spinachboul** [comment]
@fkiraly  I apologise for not being concise in stating the issue.

**Problem** : Tests are failing for detectors like `ClusterSegmenter` and `GaussianHMM`

This is the testing code the for the same:
```
from sktime.detection.hmm_learn import GuassianHMM

from sktime.detection.tests import test_all_detectors

detector = GuassianHMM.get_test_params()

failing_tests = [
    "test_predict_points",
    "test_predict_segments",
    "test_transform_output_type"
]

tester = test_all_detectors.TestAllDetectors()
tester.run_tests(
    detector,
    tests_to_run= failing_tests,
    raise_exceptions=True
)
```

Error logs for `GaussianHMM` are:

```
Traceback (most recent call last):
  File "/home/mridul/Desktop/sktime/sktime/utils/_testing/_conditional_fixtures.py", line 145, in get_fixtures
    res = generator_dict[fixture_var](test_name, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mridul/Desktop/sktime/sktime/tests/test_all_estimators.py", line 506, in _generate_estimator_instance
    return [estimator.clone()], [estimator_class.__name__]
            ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'clone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mridul/Desktop/sktime/sktime/detection/hmm_learn/test_gaussian.py", line 14, in <module>
    tester.run_tests(
  File "/home/mridul/Desktop/sktime/sktime/tests/test_all_estimators.py", line 551, in run_tests
    _, fixture_prod, fixture_names = create_conditional_fixtures_and_names(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mridul/Desktop/sktime/sktime/utils/_testing/_conditional_fixtures.py", line 180, in create_conditional_fixtures_and_names
    new_fixtures, new_fixture_names_r = get_fixtures(fixture_var, **kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mridul/Desktop/sktime/sktime/utils/_testing/_conditional_fixtures.py", line 155, in get_fixtures
    raise error
sktime.utils._testing._conditional_fixtures.FixtureGenerationError: fixture estimator_instance failed to generate. 'dict' object has no attribute 'clone'
```

Error logs for `ClusterSegmenter` are:
```
Traceback (most recent call last):
  File "/home/mridul/Desktop/sktime/sktime/utils/_testing/_conditional_fixtures.py", line 145, in get_fixtures
    res = generator_dict[fixture_var](test_name, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mridul/Desktop/sktime/sktime/tests/test_all_estimators.py", line 506, in _generate_estimator_instance
    return [estimator.clone()], [estimator_class.__name__]
            ^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'clone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mridul/Desktop/sktime/sktime/detection/hmm_learn/test_gaussian.py", line 14, in <module>
    tester.run_tests(
  File "/home/mridul/Desktop/sktime/sktime/tests/test_all_estimators.py", line 551, in run_tests
    _, fixture_prod, fixture_names = create_conditional_fixtures_and_names(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mridul/Desktop/sktime/sktime/utils/_testing/_conditional_fixtures.py", line 180, in create_conditional_fixtures_and_names
    new_fixtures, new_fixture_names_r = get_fixtures(fixture_var, **kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mridul/Desktop/sktime/sktime/utils/_testing/_conditional_fixtures.py", line 155, in get_fixtures
    raise error
sktime.utils._testing._conditional_fixtures.FixtureGenerationError: fixture estimator_instance failed to generate. 'list' object has no attribute 'clone'
```

The code lines showing the error are:
* https://github.com/sktime/sktime/blob/6271cb731044428cdc2390d809e6fd458a6b3924/sktime/tests/test_all_estimators.py#L506 
* https://github.com/sktime/sktime/blob/6271cb731044428cdc2390d809e6fd458a6b3924/sktime/utils/_testing/_conditional_fixtures.py#L180

I would request core developers to look on the issue for the same
Thanks!
